.TH "aix3adb.DataSample" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aix3adb.DataSample \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaix3adb\&.Aix3adbBaseElement\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 33 of file aix3adb\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
