.TH "python/aix3adb_deprecated.py" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/aix3adb_deprecated.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaix3adb_deprecated\&.aix3adb\fP"
.br
.ti -1c
.RI "class \fBaix3adb_deprecated\&.aix3adbAuth\fP"
.br
.ti -1c
.RI "class \fBaix3adb_deprecated\&.cookietransportrequest\fP"
.br
.ti -1c
.RI "class \fBaix3adb_deprecated\&.cookietransport\fP"
.br
.ti -1c
.RI "class \fBaix3adb_deprecated\&.cookiesafetransport\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBaix3adb_deprecated\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBaix3adb_deprecated\&.main\fP"
.br
.ti -1c
.RI "def \fBaix3adb_deprecated\&.transport\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBaix3adb_deprecated\&.log\fP = logging\&.getLogger( 'aix3adb' )"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
