.TH "aix3adbtest" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aix3adbtest \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def aix3adbtest\&.main ()"

.PP
Definition at line 3 of file aix3adbtest\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
