.TH "cesubmit.Task" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cesubmit.Task \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBload\fP"
.br
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBsave\fP"
.br
.ti -1c
.RI "def \fBaddJob\fP"
.br
.ti -1c
.RI "def \fBsubmit\fP"
.br
.ti -1c
.RI "def \fBresubmit\fP"
.br
.ti -1c
.RI "def \fBkill\fP"
.br
.ti -1c
.RI "def \fBmakePrologue\fP"
.br
.ti -1c
.RI "def \fBcreatedir\fP"
.br
.ti -1c
.RI "def \fBgetStatus\fP"
.br
.ti -1c
.RI "def \fBgetOutput\fP"
.br
.ti -1c
.RI "def \fBjobStatusNumbers\fP"
.br
.ti -1c
.RI "def \fBcleanUp\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBdirectory\fP"
.br
.ti -1c
.RI "\fBjdlfilename\fP"
.br
.ti -1c
.RI "\fBexecutable\fP"
.br
.ti -1c
.RI "\fBmode\fP"
.br
.ti -1c
.RI "\fBscramArch\fP"
.br
.ti -1c
.RI "\fBcmsswVersion\fP"
.br
.ti -1c
.RI "\fBceId\fP"
.br
.ti -1c
.RI "\fBjobs\fP"
.br
.ti -1c
.RI "\fBfrontEndStatus\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "def \fB_dosubmit\fP"
.br
.ti -1c
.RI "def \fB_getStatusMultiple\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 169 of file cesubmit\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def cesubmit\&.Task\&.__init__ (self, name, directory = \fCNone\fP, mode = \fC'RECREATE'\fP, scramArch = \fC'slc5_amd64_gcc462'\fP, cmsswVersion = \fC'CMSSW_5_3_14'\fP, ceId = \fC'grid-ce\&.physik\&.rwth-aachen\&.de:8443/cream-pbs-cms'\fP)"

.PP
Definition at line 181 of file cesubmit\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def cesubmit\&.Task\&._dosubmit (self, nodeids, processes, worker)\fC [private]\fP"

.PP
Definition at line 233 of file cesubmit\&.py\&.
.PP
References cesubmit\&.Task\&.jobs\&.
.PP
Referenced by cesubmit\&.Task\&.kill(), cesubmit\&.Task\&.resubmit(), and cesubmit\&.Task\&.submit()\&.
.SS "def cesubmit\&.Task\&._getStatusMultiple (self)\fC [private]\fP"

.PP
Definition at line 303 of file cesubmit\&.py\&.
.PP
References cesubmit\&.Task\&.jobs, cesubmit\&.Task\&.name, and cesubmit\&.parseStatusMultipleL1()\&.
.PP
Referenced by cesubmit\&.Task\&.getStatus()\&.
.SS "def cesubmit\&.Task\&.addJob (self, job)"

.PP
Definition at line 207 of file cesubmit\&.py\&.
.SS "def cesubmit\&.Task\&.cleanUp (self)"

.PP
Definition at line 396 of file cesubmit\&.py\&.
.PP
References cesubmit\&.Task\&.directory, cesubmit\&.Task\&.jobs, and cesubmit\&.Task\&.name\&.
.PP
Referenced by cesubmit\&.Task\&.kill(), and cesubmit\&.Task\&.resubmit()\&.
.SS "def cesubmit\&.Task\&.createdir (self)"

.PP
Definition at line 297 of file cesubmit\&.py\&.
.PP
References cesubmit\&.Task\&.directory, and cesubmit\&.Task\&.mode\&.
.PP
Referenced by cesubmit\&.Task\&.submit()\&.
.SS "def cesubmit\&.Task\&.getOutput (self, connections = \fC1\fP)"

.PP
Definition at line 348 of file cesubmit\&.py\&.
.PP
References cesubmit\&.chunks(), cesubmit\&.Task\&.directory, cesubmit\&.Task\&.jobs, cesubmit\&.Task\&.name, cesubmit\&.parseGetOutput(), and cesubmit\&.Task\&.save()\&.
.SS "def cesubmit\&.Task\&.getStatus (self)"

.PP
Definition at line 325 of file cesubmit\&.py\&.
.PP
References cesubmit\&.Task\&._getStatusMultiple(), cesubmit\&.Job\&.frontEndStatus, cesubmit\&.Task\&.frontEndStatus, cesubmit\&.Task\&.jobs, cesubmit\&.Task\&.name, and cesubmit\&.Task\&.save()\&.
.SS "def cesubmit\&.Task\&.jobStatusNumbers (self)"

.PP
Definition at line 375 of file cesubmit\&.py\&.
.PP
References cesubmit\&.Task\&.jobs\&.
.SS "def cesubmit\&.Task\&.kill (self, nodeids, processes = \fC0\fP)"

.PP
Definition at line 257 of file cesubmit\&.py\&.
.PP
References cesubmit\&.Task\&._dosubmit(), cesubmit\&.Task\&.cleanUp(), cesubmit\&.Task\&.name, and cesubmit\&.Task\&.save()\&.
.SS "def cesubmit\&.Task\&.load (cls, directory)"

.PP
Definition at line 171 of file cesubmit\&.py\&.
.SS "def cesubmit\&.Task\&.makePrologue (self)"

.PP
Definition at line 263 of file cesubmit\&.py\&.
.PP
References cesubmit\&.Task\&.cmsswVersion, and cesubmit\&.Task\&.scramArch\&.
.PP
Referenced by cesubmit\&.Task\&.submit()\&.
.SS "def cesubmit\&.Task\&.resubmit (self, nodeids, processes = \fC0\fP)"

.PP
Definition at line 250 of file cesubmit\&.py\&.
.PP
References cesubmit\&.Task\&._dosubmit(), cesubmit\&.Task\&.cleanUp(), cesubmit\&.Job\&.frontEndStatus, cesubmit\&.Task\&.frontEndStatus, cesubmit\&.Task\&.name, and cesubmit\&.Task\&.save()\&.
.SS "def cesubmit\&.Task\&.save (self)"

.PP
Definition at line 195 of file cesubmit\&.py\&.
.PP
References cesubmit\&.Task\&.directory, cesubmit\&.Task\&.jobs, and cesubmit\&.Task\&.name\&.
.PP
Referenced by cesubmit\&.Task\&.getOutput(), cesubmit\&.Task\&.getStatus(), cesubmit\&.Task\&.kill(), cesubmit\&.Task\&.resubmit(), and cesubmit\&.Task\&.submit()\&.
.SS "def cesubmit\&.Task\&.submit (self, processes = \fC0\fP)"

.PP
Definition at line 210 of file cesubmit\&.py\&.
.PP
References cesubmit\&.Task\&._dosubmit(), cesubmit\&.checkAndRenewVomsProxy(), cesubmit\&.Task\&.createdir(), cesubmit\&.Task\&.directory, cesubmit\&.Job\&.frontEndStatus, cesubmit\&.Task\&.frontEndStatus, cesubmit\&.Task\&.jobs, cesubmit\&.Task\&.makePrologue(), cesubmit\&.Task\&.name, and cesubmit\&.Task\&.save()\&.
.SH "Member Data Documentation"
.PP 
.SS "cesubmit\&.Task\&.ceId"

.PP
Definition at line 192 of file cesubmit\&.py\&.
.SS "cesubmit\&.Task\&.cmsswVersion"

.PP
Definition at line 191 of file cesubmit\&.py\&.
.PP
Referenced by cesubmit\&.Task\&.makePrologue()\&.
.SS "cesubmit\&.Task\&.directory"

.PP
Definition at line 183 of file cesubmit\&.py\&.
.PP
Referenced by cesubmit\&.Task\&.cleanUp(), cesubmit\&.Task\&.createdir(), cesubmit\&.Task\&.getOutput(), cesubmit\&.Task\&.save(), and cesubmit\&.Task\&.submit()\&.
.SS "cesubmit\&.Task\&.executable"

.PP
Definition at line 188 of file cesubmit\&.py\&.
.SS "cesubmit\&.Task\&.frontEndStatus"

.PP
Definition at line 194 of file cesubmit\&.py\&.
.PP
Referenced by cesubmit\&.Task\&.getStatus(), cesubmit\&.Task\&.resubmit(), and cesubmit\&.Task\&.submit()\&.
.SS "cesubmit\&.Task\&.jdlfilename"

.PP
Definition at line 187 of file cesubmit\&.py\&.
.SS "cesubmit\&.Task\&.jobs"

.PP
Definition at line 193 of file cesubmit\&.py\&.
.PP
Referenced by cesubmit\&.Task\&._dosubmit(), cesubmit\&.Task\&._getStatusMultiple(), cesubmit\&.Task\&.cleanUp(), cesubmit\&.Task\&.getOutput(), cesubmit\&.Task\&.getStatus(), cesubmit\&.Task\&.jobStatusNumbers(), cesubmit\&.Task\&.save(), cesubmit\&.Task\&.submit(), crabFunctions\&.CrabTask\&.update(), and crabFunctions\&.CrabTask\&.updateJobStats()\&.
.SS "cesubmit\&.Task\&.mode"

.PP
Definition at line 189 of file cesubmit\&.py\&.
.PP
Referenced by cesubmit\&.Task\&.createdir()\&.
.SS "cesubmit\&.Task\&.name"

.PP
Definition at line 182 of file cesubmit\&.py\&.
.PP
Referenced by cesubmit\&.Task\&._getStatusMultiple(), cesubmit\&.Task\&.cleanUp(), cesubmit\&.Task\&.getOutput(), cesubmit\&.Task\&.getStatus(), cesubmit\&.Task\&.kill(), cesubmit\&.Task\&.resubmit(), cesubmit\&.Task\&.save(), cesubmit\&.Task\&.submit(), and crabFunctions\&.CrabTask\&.update()\&.
.SS "cesubmit\&.Task\&.scramArch"

.PP
Definition at line 190 of file cesubmit\&.py\&.
.PP
Referenced by cesubmit\&.Task\&.makePrologue()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
