cesubmit
NAME
cesubmit -
SYNOPSIS
Classes
class Job
class Task
class ProxyError
Functions
def submitWorker
def resubmitWorker
def killWorker
def parseGetOutput
def parseStatus
def parseStatusMultiple
def parseStatusMultipleL1
def chunks
def timeLeftVomsProxy
def checkVomsProxy
def renewVomsProxy
def checkAndRenewVomsProxy
Variables
tuple log = logging.getLogger(__name__)
Function Documentation
def cesubmit.checkAndRenewVomsProxy (time = 604800, voms = 'cms:/cms/dcms', passphrase = None)
Definition at line 514 of file cesubmit.py.
References checkVomsProxy(), and renewVomsProxy().
Referenced by cesubmit.Job.submit(), and cesubmit.Task.submit().
def cesubmit.checkVomsProxy (time = 86400)
Returns True if the proxy is valid longer than time, False otherwise.
Definition at line 496 of file cesubmit.py.
References timeLeftVomsProxy().
Referenced by checkAndRenewVomsProxy().
def cesubmit.chunks (l, n)
Yield successive n-sized chunks from l.
Definition at line 476 of file cesubmit.py.
Referenced by cesubmit.Task.getOutput().
def cesubmit.killWorker (job)
Definition at line 25 of file cesubmit.py.
def cesubmit.parseGetOutput (stdout)
Definition at line 410 of file cesubmit.py.
Referenced by cesubmit.Task.getOutput().
def cesubmit.parseStatus (stdout)
Definition at line 424 of file cesubmit.py.
def cesubmit.parseStatusMultiple (stdout)
Definition at line 436 of file cesubmit.py.
def cesubmit.parseStatusMultipleL1 (stdout)
Definition at line 452 of file cesubmit.py.
Referenced by cesubmit.Task._getStatusMultiple().
def cesubmit.renewVomsProxy (voms = 'cms:/cms/dcms', passphrase = None)
Make a new proxy with a lifetime of one week.
Definition at line 501 of file cesubmit.py.
Referenced by checkAndRenewVomsProxy().
def cesubmit.resubmitWorker (job)
Definition at line 21 of file cesubmit.py.
def cesubmit.submitWorker (job)
Definition at line 17 of file cesubmit.py.
def cesubmit.timeLeftVomsProxy ()
Definition at line 485 of file cesubmit.py.
Referenced by checkVomsProxy().
Variable Documentation
tuple cesubmit.log = logging.getLogger(__name__)
Definition at line 14 of file cesubmit.py.
Author
Generated automatically by Doxygen for libs3a from the source code.