.TH "cesubmit" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cesubmit \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJob\fP"
.br
.ti -1c
.RI "class \fBTask\fP"
.br
.ti -1c
.RI "class \fBProxyError\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsubmitWorker\fP"
.br
.ti -1c
.RI "def \fBresubmitWorker\fP"
.br
.ti -1c
.RI "def \fBkillWorker\fP"
.br
.ti -1c
.RI "def \fBparseGetOutput\fP"
.br
.ti -1c
.RI "def \fBparseStatus\fP"
.br
.ti -1c
.RI "def \fBparseStatusMultiple\fP"
.br
.ti -1c
.RI "def \fBparseStatusMultipleL1\fP"
.br
.ti -1c
.RI "def \fBchunks\fP"
.br
.ti -1c
.RI "def \fBtimeLeftVomsProxy\fP"
.br
.ti -1c
.RI "def \fBcheckVomsProxy\fP"
.br
.ti -1c
.RI "def \fBrenewVomsProxy\fP"
.br
.ti -1c
.RI "def \fBcheckAndRenewVomsProxy\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBlog\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def cesubmit\&.checkAndRenewVomsProxy (time = \fC604800\fP, voms = \fC'cms:/cms/dcms'\fP, passphrase = \fCNone\fP)"

.PP
Definition at line 514 of file cesubmit\&.py\&.
.PP
References checkVomsProxy(), and renewVomsProxy()\&.
.PP
Referenced by cesubmit\&.Job\&.submit(), and cesubmit\&.Task\&.submit()\&.
.SS "def cesubmit\&.checkVomsProxy (time = \fC86400\fP)"

.PP
.nf
Returns True if the proxy is valid longer than time, False otherwise.
.fi
.PP
 
.PP
Definition at line 496 of file cesubmit\&.py\&.
.PP
References timeLeftVomsProxy()\&.
.PP
Referenced by checkAndRenewVomsProxy()\&.
.SS "def cesubmit\&.chunks (l, n)"

.PP
.nf
Yield successive n-sized chunks from l.

.fi
.PP
 
.PP
Definition at line 476 of file cesubmit\&.py\&.
.PP
Referenced by cesubmit\&.Task\&.getOutput()\&.
.SS "def cesubmit\&.killWorker (job)"

.PP
Definition at line 25 of file cesubmit\&.py\&.
.SS "def cesubmit\&.parseGetOutput (stdout)"

.PP
Definition at line 410 of file cesubmit\&.py\&.
.PP
Referenced by cesubmit\&.Task\&.getOutput()\&.
.SS "def cesubmit\&.parseStatus (stdout)"

.PP
Definition at line 424 of file cesubmit\&.py\&.
.SS "def cesubmit\&.parseStatusMultiple (stdout)"

.PP
Definition at line 436 of file cesubmit\&.py\&.
.SS "def cesubmit\&.parseStatusMultipleL1 (stdout)"

.PP
Definition at line 452 of file cesubmit\&.py\&.
.PP
Referenced by cesubmit\&.Task\&._getStatusMultiple()\&.
.SS "def cesubmit\&.renewVomsProxy (voms = \fC'cms:/cms/dcms'\fP, passphrase = \fCNone\fP)"

.PP
.nf
Make a new proxy with a lifetime of one week.
.fi
.PP
 
.PP
Definition at line 501 of file cesubmit\&.py\&.
.PP
Referenced by checkAndRenewVomsProxy()\&.
.SS "def cesubmit\&.resubmitWorker (job)"

.PP
Definition at line 21 of file cesubmit\&.py\&.
.SS "def cesubmit\&.submitWorker (job)"

.PP
Definition at line 17 of file cesubmit\&.py\&.
.SS "def cesubmit\&.timeLeftVomsProxy ()"

.PP
Definition at line 485 of file cesubmit\&.py\&.
.PP
Referenced by checkVomsProxy()\&.
.SH "Variable Documentation"
.PP 
.SS "tuple cesubmit\&.log = logging\&.getLogger(__name__)"

.PP
Definition at line 14 of file cesubmit\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
