.TH "crabFunctions.CrabTask" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crabFunctions.CrabTask \- 
.PP
Class for a single CrabRequest\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIThe object constructor\&. \fP"
.ti -1c
.RI "def \fBupdate\fP"
.br
.RI "\fIFunction to update Task in associated Jobs\&. \fP"
.ti -1c
.RI "def \fBupdateJobStats\fP"
.br
.RI "\fIFunction to update JobStatistics\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBuuid\fP"
.br
.ti -1c
.RI "\fBcontroller\fP"
.br
.ti -1c
.RI "\fBjobs\fP"
.br
.ti -1c
.RI "\fBlocalDir\fP"
.br
.ti -1c
.RI "\fBoutlfn\fP"
.br
.ti -1c
.RI "\fBStorageFileList\fP"
.br
.ti -1c
.RI "\fBisUpdating\fP"
.br
.ti -1c
.RI "\fBnJobs\fP"
.br
.ti -1c
.RI "\fBstate\fP"
.br
.ti -1c
.RI "\fBmaxjobnumber\fP"
.br
.ti -1c
.RI "\fBnUnsubmitted\fP"
.br
.ti -1c
.RI "\fBnIdle\fP"
.br
.ti -1c
.RI "\fBnRunning\fP"
.br
.ti -1c
.RI "\fBnTransferring\fP"
.br
.ti -1c
.RI "\fBnCooloff\fP"
.br
.ti -1c
.RI "\fBnFailed\fP"
.br
.ti -1c
.RI "\fBnFinished\fP"
.br
.ti -1c
.RI "\fBnComplete\fP"
.br
.ti -1c
.RI "\fBlastUpdate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for a single CrabRequest\&. 

This class represents one crab3 task/request 
.PP
Definition at line 253 of file crabFunctions\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def crabFunctions\&.CrabTask\&.__init__ (self, taskname, crabController = \fCNone\fP, initUpdate = \fCTrue\fP, localDir = \fC''\fP, outlfn = \fC''\fP, StorageFileList = \fC[]\fP)"

.PP
The object constructor\&. self: \fBCrabTask\fP 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&.  taskname: String 
.br
\fItaskname,:\fP The object pointer\&.  initUpdate: Boolean 
.br
\fIinitUpdate,:\fP Flag if crab status should be called when an instance is created 
.RE
.PP

.PP
Definition at line 263 of file crabFunctions\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def crabFunctions\&.CrabTask\&.update (self)"

.PP
Function to update Task in associated Jobs\&. self: \fBCrabTask\fP 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&. 
.RE
.PP

.PP
Definition at line 298 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabTask\&.isUpdating, cesubmit\&.Task\&.jobs, crabFunctions\&.CrabTask\&.jobs, cesubmit\&.Task\&.name, crabFunctions\&.CrabTask\&.name, crabFunctions\&.CrabTask\&.nJobs, crabFunctions\&.CrabTask\&.state, and crabFunctions\&.CrabTask\&.updateJobStats()\&.
.SS "def crabFunctions\&.CrabTask\&.updateJobStats (self, dCacheFileList = \fCNone\fP)"

.PP
Function to update JobStatistics\&. self: \fBCrabTask\fP 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&.  dCacheFilelist: list of strings 
.br
\fIdCacheFilelist,:\fP A list of files on the dCache 
.RE
.PP

.PP
Definition at line 319 of file crabFunctions\&.py\&.
.PP
References cesubmit\&.Task\&.jobs, crabFunctions\&.CrabTask\&.jobs, and crabFunctions\&.CrabTask\&.nComplete\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SH "Member Data Documentation"
.PP 
.SS "crabFunctions\&.CrabTask\&.controller"

.PP
Definition at line 268 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.isUpdating"

.PP
Definition at line 275 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "crabFunctions\&.CrabTask\&.jobs"

.PP
Definition at line 271 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update(), and crabFunctions\&.CrabTask\&.updateJobStats()\&.
.SS "crabFunctions\&.CrabTask\&.lastUpdate"

.PP
Definition at line 306 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.localDir"

.PP
Definition at line 272 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.maxjobnumber"

.PP
Definition at line 279 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.name"

.PP
Definition at line 264 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "crabFunctions\&.CrabTask\&.nComplete"

.PP
Definition at line 287 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.updateJobStats()\&.
.SS "crabFunctions\&.CrabTask\&.nCooloff"

.PP
Definition at line 284 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.nFailed"

.PP
Definition at line 285 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.nFinished"

.PP
Definition at line 286 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.nIdle"

.PP
Definition at line 281 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.nJobs"

.PP
Definition at line 277 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "crabFunctions\&.CrabTask\&.nRunning"

.PP
Definition at line 282 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.nTransferring"

.PP
Definition at line 283 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.nUnsubmitted"

.PP
Definition at line 280 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.outlfn"

.PP
Definition at line 273 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.state"

.PP
Definition at line 278 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabTask\&.update()\&.
.SS "crabFunctions\&.CrabTask\&.StorageFileList"

.PP
Definition at line 274 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabTask\&.uuid"

.PP
Definition at line 265 of file crabFunctions\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
