.TH "python/crabFunctions.py.BACKUP.13247.py" 3 "6 Nov 2014" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/crabFunctions.py.BACKUP.13247.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcrabFunctions::CrabController\fP"
.br
.RI "\fIThe \fBCrabController\fP class. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcrabFunctions\fP"
.br
.PP

.RI "\fIThis module provides common functions for tasks with crab3. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code.
