.TH "python/crabFunctions.py.BASE.12994.py" 3 "6 Nov 2014" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/crabFunctions.py.BASE.12994.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcrabFunctions\fP"
.br
.PP

.RI "\fIThis module provides common functions for tasks with crab3. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcrabFunctions::crab_checkwrite\fP"
.br
.RI "\fICheck if crab can write to specified site. \fP"
.ti -1c
.RI "def \fBcrabFunctions::crab_submit\fP"
.br
.RI "\fICheck if crab can write to specified site. \fP"
.ti -1c
.RI "def \fBcrabFunctions::crab_checkHNname\fP"
.br
.RI "\fIReturns the hn name for a user with valid proxy. \fP"
.ti -1c
.RI "def \fBcrabFunctions::crab_status\fP"
.br
.RI "\fICheck crab status. \fP"
.ti -1c
.RI "def \fBcrabFunctions::conditionalLog\fP"
.br
.RI "\fIPrints log message either to logging object if given or print log message to prompt. \fP"
.ti -1c
.RI "def \fBcrabFunctions::crab_commandlineOptions\fP"
.br
.RI "\fIPopulates a existing optparse parser or returns a new one with all options for crab functions. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code.
