.TH "python/crabFunctions.py" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/crabFunctions.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcrabFunctions\&.CrabController\fP"
.br
.RI "\fIThe \fBCrabController\fP class\&. \fP"
.ti -1c
.RI "class \fBcrabFunctions\&.CrabTask\fP"
.br
.RI "\fIClass for a single CrabRequest\&. \fP"
.ti -1c
.RI "class \fBcrabFunctions\&.TaskStats\fP"
.br
.RI "\fIClass holds job statistics for several Crab tasks\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBcrabFunctions\fP"
.br
.RI "\fIThis module provides common functions for tasks with crab3\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
