.TH "curseshelpers.CursesHandler" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curseshelpers.CursesHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Handler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBemit\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbottomText\fP"
.br
.ti -1c
.RI "\fBstdscr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 426 of file curseshelpers\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def curseshelpers\&.CursesHandler\&.__init__ (self, stdscr, bottomText, level = \fClogging\&.DEBUG\fP)"

.PP
Definition at line 428 of file curseshelpers\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def curseshelpers\&.CursesHandler\&.emit (self, record)"

.PP
Definition at line 432 of file curseshelpers\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "curseshelpers\&.CursesHandler\&.bottomText"

.PP
Definition at line 430 of file curseshelpers\&.py\&.
.SS "curseshelpers\&.CursesHandler\&.stdscr"

.PP
Definition at line 431 of file curseshelpers\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
