.TH "HistClass" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HistClass \- 
.PP
Functions to have easy histogram handling\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBCreateHisto\fP (Int_t n_histos, const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')"
.br
.RI "\fIFunction to create a number of 1D histograms in the histo map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBCreateHisto\fP (Int_t n_histos, const char *name, const char *particle, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')"
.br
.RI "\fIFunction to create a number of 1D histograms in the histo map for a specific particle\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBCreateHistoUnchangedName\fP (const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')"
.br
.RI "\fIFunction to create a 1D histogram in the histo map without the standard histogram naming convention (h1_\&.\&.\&.) \fP"
.ti -1c
.RI "\fBSUPPRESS_NOT_USED_WARN\fP static 
.br
const void \fBCreateHisto\fP (const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')"
.br
.RI "\fIFunction to create one 1D histograms in the histo map\&. \fP"
.ti -1c
.RI "\fBSUPPRESS_NOT_USED_WARN\fP static 
.br
const void \fBCreateHisto\fP (const char *name, const char *particle, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')"
.br
.RI "\fIFunction to create one 1D histogram in the histo map for a specific particle\&. \fP"
.ti -1c
.RI "\fBSUPPRESS_NOT_USED_WARN\fP static 
.br
const void \fBCreateHisto\fP (boost::basic_format< char > name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')"
.br
.RI "\fIFunction to create one 1D histograms in the histo map with a boost name as input\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBCreateHisto\fP (const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t ylow, Double_t yup, TString xtitle='', TString ytitle='')"
.br
.RI "\fIFunction to create one 2D histograms in the histo map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBCreateNSparse\fP (const char *name, int dimension, int *bins, double *xmin, double *xmax, string axisTitle[])"
.br
.RI "\fIFunction to create one NSparse in the nSparse map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBCreateTree\fP (const char *name, const char *varlist, int bufsize)"
.br
.RI "\fIFunction to create one NtupleD in the NtupleD map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBCreateTree\fP (std::map< std::string, float > &m, const char *name)"
.br
.RI "\fIFunction to create one Tree in the TTree map\&. \fP"
.ti -1c
.RI "static void \fBFill\fP (Int_t n_histo, const char *name, double value, double weight)"
.br
.RI "\fIFunction to fill an event in a 1D histogram of the map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBFill\fP (Int_t n_histo, std::string name, double value, double weight)"
.br
.RI "\fIFunction to fill an event in a 1D histogram of the map with a string as histo name\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBFill\fP (const char *name, double value, double weight)"
.br
.RI "\fIFunction to fill an event in a 1D histogram of the map without histo number\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBFill\fP (const char *name, double valuex, double valuey, double weight)"
.br
.RI "\fIFunction to fill an event in a 2D histogram of the map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBFillSparse\fP (const char *name, int n,\&.\&.\&.)"
.br
.RI "\fIFunction to fill an event in a nSparse of the nSparse map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBFillTree\fP (const char *name, double *values)"
.br
.RI "\fIFunction to fill an event in a NTupleD of the map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBFillTree\fP (const char *name)"
.br
.RI "\fIFunction to fill an event in a TTree of the map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBWrite\fP (Int_t n_histo, const char *name)"
.br
.RI "\fIFunction to write one 1D histogram of the map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBWrite\fP (const char *name)"
.br
.RI "\fIFunction to write one 1D histogram of the map without number\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBWriteAll\fP (const char *name='')"
.br
.RI "\fIFunction to write many 1D histograms of the map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBWriteAll2\fP (const char *name='')"
.br
.RI "\fIFunction to write many 2D histograms of the map\&. \fP"
.ti -1c
.RI "\fBSUPPRESS_NOT_USED_WARN\fP void \fBsplit\fP (const std::string &s, char delim, std::vector< std::string > &elems)"
.br
.RI "\fIFunction split a string at a delimiter\&. \fP"
.ti -1c
.RI "\fBSUPPRESS_NOT_USED_WARN\fP 
.br
std::vector< std::string > \fBsplit\fP (const std::string &s, char delim)"
.br
.RI "\fIFunction split a string at a delimiter and return the results\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBWriteAll\fP (const char *name, const char *contains_i)"
.br
.RI "\fIFunction to write many 1D histograms which contain specific strings of the map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBWriteAll2\fP (const char *name, const char *contains_i)"
.br
.RI "\fIFunction to write many 2D histograms which contain specific strings of the map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBWriteAll\fP (const char *name, const char *contains_i, const char *vetos_i)"
.br
.RI "\fIFunction to write many 1D histograms which (not) contain specific strings of the map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBWriteAll2\fP (const char *name, const char *contains_i, const char *vetos_i)"
.br
.RI "\fIFunction to write many 2D histograms which (not) contain specific strings of the map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBWriteAllTrees\fP (const char *name='')"
.br
.RI "\fIFunction to write many TTrees and TNtupleDs of the maps\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBWriteN\fP (const char *name='')"
.br
.RI "\fIFunction to write many TNsparses of the map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBWrite2\fP (const char *name)"
.br
.RI "\fIFunction to write one 2D histogram of the map\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBSetToZero\fP (Int_t n_histo, const char *name)"
.br
.RI "\fIFunction to set all negative bin contents to zero for a 1D histogram\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP 
.br
TH1D * \fBReturnHist\fP (const char *name)"
.br
.RI "\fIFunction to get one 1D histogram from the map without number\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBNameBins\fP (const char *name, const uint n_bins, TString *d_mydisc)"
.br
.RI "\fIFunction to give one 1D histogram from the map alphanumeric bin labels without number\&. \fP"
.ti -1c
.RI "static \fBSUPPRESS_NOT_USED_WARN\fP void \fBNameBins\fP (Int_t n_histo, const char *name, const uint n_bins, TString *d_mydisc)"
.br
.RI "\fIFunction to give one 1D histogram from the map alphanumeric bin labels\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static std::map< std::string, 
.br
TH1D * > \fBhisto\fP"
.br
.ti -1c
.RI "static std::map< std::string, 
.br
TH2D * > \fBhisto2\fP"
.br
.ti -1c
.RI "static std::map< std::string, 
.br
THnSparseD * > \fBhiston\fP"
.br
.ti -1c
.RI "static std::map< std::string, 
.br
TNtupleD * > \fBttupple\fP"
.br
.ti -1c
.RI "static std::map< std::string, 
.br
TTree * > \fBtrees\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to have easy histogram handling\&. 

In this namespace different functions to interact with the histogram map are included, to create, fill and write histograms in a convinient way\&. 
.SH "Function Documentation"
.PP 
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::CreateHisto (Int_tn_histos, const char *name, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = \fC''\fP)\fC [static]\fP"

.PP
Function to create a number of 1D histograms in the histo map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn_histos\fP Number of histograms that should be created with different numbers 
.br
\fIname\fP Name of the histograms that should be created 
.br
\fInbinsx\fP Number of bins on the x-axis 
.br
\fIxlow\fP Lower edge of the x-axis 
.br
\fIxup\fP Upper edge of the x-axis 
.br
\fIxtitle\fP Optinal title of the x-axis (DEFAULT = '') 
.RE
.PP

.PP
Definition at line 48 of file HistClass\&.hh\&.
.PP
References histo\&.
.PP
Referenced by CreateHisto()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::CreateHisto (Int_tn_histos, const char *name, const char *particle, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = \fC''\fP)\fC [static]\fP"

.PP
Function to create a number of 1D histograms in the histo map for a specific particle\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn_histos\fP Number of histograms that should be created with different numbers 
.br
\fIname\fP Name of the histograms that should be created 
.br
\fIparticle\fP Name of the particle for which the histograms are created 
.br
\fInbinsx\fP Number of bins on the x-axis 
.br
\fIxlow\fP Lower edge of the x-axis 
.br
\fIxup\fP Upper edge of the x-axis 
.br
\fIxtitle\fP Optinal title of the x-axis (DEFAULT = '') 
.RE
.PP

.PP
Definition at line 68 of file HistClass\&.hh\&.
.PP
References histo\&.
.SS "\fBSUPPRESS_NOT_USED_WARN\fP static const void HistClass::CreateHisto (const char *name, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = \fC''\fP)\fC [static]\fP"

.PP
Function to create one 1D histograms in the histo map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the histogram that should be created 
.br
\fInbinsx\fP Number of bins on the x-axis 
.br
\fIxlow\fP Lower edge of the x-axis 
.br
\fIxup\fP Upper edge of the x-axis 
.br
\fIxtitle\fP Optinal title of the x-axis (DEFAULT = '') 
.RE
.PP

.PP
Definition at line 102 of file HistClass\&.hh\&.
.PP
References histo\&.
.SS "\fBSUPPRESS_NOT_USED_WARN\fP static const void HistClass::CreateHisto (const char *name, const char *particle, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = \fC''\fP)\fC [static]\fP"

.PP
Function to create one 1D histogram in the histo map for a specific particle\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the histograms that should be created 
.br
\fIparticle\fP Name of the particle for which the histograms are created 
.br
\fInbinsx\fP Number of bins on the x-axis 
.br
\fIxlow\fP Lower edge of the x-axis 
.br
\fIxup\fP Upper edge of the x-axis 
.br
\fIxtitle\fP Optinal title of the x-axis (DEFAULT = '') 
.RE
.PP

.PP
Definition at line 119 of file HistClass\&.hh\&.
.PP
References histo\&.
.SS "\fBSUPPRESS_NOT_USED_WARN\fP static const void HistClass::CreateHisto (boost::basic_format< char >name, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = \fC''\fP)\fC [static]\fP"

.PP
Function to create one 1D histograms in the histo map with a boost name as input\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the histogram that should be created (boost::basic_format) 
.br
\fInbinsx\fP Number of bins on the x-axis 
.br
\fIxlow\fP Lower edge of the x-axis 
.br
\fIxup\fP Upper edge of the x-axis 
.br
\fIxtitle\fP Optinal title of the x-axis (DEFAULT = '') 
.RE
.PP

.PP
Definition at line 135 of file HistClass\&.hh\&.
.PP
References CreateHisto()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::CreateHisto (const char *name, Int_tnbinsx, Double_txlow, Double_txup, Int_tnbinsy, Double_tylow, Double_tyup, TStringxtitle = \fC''\fP, TStringytitle = \fC''\fP)\fC [static]\fP"

.PP
Function to create one 2D histograms in the histo map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the histogram that should be created 
.br
\fInbinsx\fP Number of bins on the x-axis 
.br
\fIxlow\fP Lower edge of the x-axis 
.br
\fIxup\fP Upper edge of the x-axis 
.br
\fInbinsy\fP Number of bins on the y-axis 
.br
\fIylow\fP Lower edge of the y-axis 
.br
\fIyup\fP Upper edge of the y-axis 
.br
\fIxtitle\fP Optinal title of the x-axis (DEFAULT = '') 
.br
\fIytitle\fP Optinal title of the y-axis (DEFAULT = '') 
.RE
.PP

.PP
Definition at line 152 of file HistClass\&.hh\&.
.PP
References html_to_bash_ascii_converter::dummy, and histo2\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::CreateHistoUnchangedName (const char *name, Int_tnbinsx, Double_txlow, Double_txup, TStringxtitle = \fC''\fP)\fC [static]\fP"

.PP
Function to create a 1D histogram in the histo map without the standard histogram naming convention (h1_\&.\&.\&.) 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the histograms that should be created 
.br
\fInbinsx\fP Number of bins on the x-axis 
.br
\fIxlow\fP Lower edge of the x-axis 
.br
\fIxup\fP Upper edge of the x-axis 
.br
\fIxtitle\fP Optinal title of the x-axis (DEFAULT = '') 
.RE
.PP

.PP
Definition at line 86 of file HistClass\&.hh\&.
.PP
References histo\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::CreateNSparse (const char *name, intdimension, int *bins, double *xmin, double *xmax, stringaxisTitle[])\fC [static]\fP"

.PP
Function to create one NSparse in the nSparse map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the NSparse that should be created 
.br
\fIdimension\fP Number of dimensions that the NSparse should have 
.br
\fIbins\fP Array with the number of bins for each dimension 
.br
\fIxmin\fP Array of the lower edge of the axis for each dimension 
.br
\fIxmax\fP Array of the upper edge of the axis for each dimension 
.br
\fIaxisTitle[]\fP Array of the axis title for each dimension 
.RE
.PP

.PP
Definition at line 170 of file HistClass\&.hh\&.
.PP
References html_to_bash_ascii_converter::dummy, and histon\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::CreateTree (const char *name, const char *varlist, intbufsize)\fC [static]\fP"

.PP
Function to create one NtupleD in the NtupleD map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the NSparse that should be created 
.br
\fIvarlist\fP Colon sepereated list with the name of the branches that should be created 
.br
\fIbufsize\fP Buffer size that the NtupleD should have 
.RE
.PP

.PP
Definition at line 186 of file HistClass\&.hh\&.
.PP
References html_to_bash_ascii_converter::dummy, and ttupple\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::CreateTree (std::map< std::string, float > &m, const char *name)\fC [static]\fP"

.PP
Function to create one Tree in the TTree map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIm\fP Map of the name and variable that should be matched to each branch 
.br
\fIname\fP Name of the TTree that should be created 
.RE
.PP

.PP
Definition at line 197 of file HistClass\&.hh\&.
.PP
References trees\&.
.SS "static void HistClass::Fill (Int_tn_histo, const char *name, doublevalue, doubleweight)\fC [static]\fP"

.PP
Function to fill an event in a 1D histogram of the map\&. This function fills one value with one weight for one event in one specific histogram\&. The function also checks if the histogram exists in the map, otherwise it will print an error message\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn_histo\fP Number of the histogram that should be filled 
.br
\fIname\fP Name of the histogram which should be filled 
.br
\fIvalue\fP Value that should be filled 
.br
\fIweight\fP Weight of the event that should be filled 
.RE
.PP

.PP
Definition at line 215 of file HistClass\&.hh\&.
.PP
References histo\&.
.PP
Referenced by Fill()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::Fill (Int_tn_histo, std::stringname, doublevalue, doubleweight)\fC [static]\fP"

.PP
Function to fill an event in a 1D histogram of the map with a string as histo name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn_histo\fP Number of the histogram that should be filled 
.br
\fIname\fP Name of the histogram which should be filled (std string) 
.br
\fIvalue\fP Value that should be filled 
.br
\fIweight\fP Weight of the event that should be filled 
.RE
.PP

.PP
Definition at line 232 of file HistClass\&.hh\&.
.PP
References Fill()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::Fill (const char *name, doublevalue, doubleweight)\fC [static]\fP"

.PP
Function to fill an event in a 1D histogram of the map without histo number\&. This function fills one value with one weight for one event in one specific histogram\&. The function also checks if the histogram exists in the map, otherwise it will print an error message\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the histogram which should be filled 
.br
\fIvalue\fP Value that should be filled 
.br
\fIweight\fP Weight of the event that should be filled 
.RE
.PP

.PP
Definition at line 246 of file HistClass\&.hh\&.
.PP
References histo\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::Fill (const char *name, doublevaluex, doublevaluey, doubleweight)\fC [static]\fP"

.PP
Function to fill an event in a 2D histogram of the map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the histogram which should be filled 
.br
\fIvaluex\fP x-value that should be filled 
.br
\fIvaluey\fP y-value that should be filled 
.br
\fIweight\fP Weight of the event that should be filled 
.RE
.PP

.PP
Definition at line 270 of file HistClass\&.hh\&.
.PP
References html_to_bash_ascii_converter::dummy, and histo2\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::FillSparse (const char *name, intn, \&.\&.\&.)\fC [static]\fP"

.PP
Function to fill an event in a nSparse of the nSparse map\&. This function fills one value with one event in one specific nSparse\&. The function also checks if the nSparse exists in the map, otherwise it will print an error message\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the n which should be filled 
.br
\fIn\fP 
.br
\fI\&.\&.\&.\fP 
.RE
.PP
\fBTodo\fP
.RS 4
complete the function 
.RE
.PP

.PP
Definition at line 286 of file HistClass\&.hh\&.
.PP
References histon\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::FillTree (const char *name, double *values)\fC [static]\fP"

.PP
Function to fill an event in a NTupleD of the map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the NTupleD which should be filled 
.br
\fIvalues\fP Array of values that should be filled 
.RE
.PP

.PP
Definition at line 308 of file HistClass\&.hh\&.
.PP
References html_to_bash_ascii_converter::dummy, and ttupple\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::FillTree (const char *name)\fC [static]\fP"

.PP
Function to fill an event in a TTree of the map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the TTree which should be filled 
.RE
.PP

.PP
Definition at line 318 of file HistClass\&.hh\&.
.PP
References trees\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::NameBins (const char *name, const uintn_bins, TString *d_mydisc)\fC [static]\fP"

.PP
Function to give one 1D histogram from the map alphanumeric bin labels without number\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the histogram that should get bin names 
.br
\fIn_bins\fP of bins that should be renamed 
.br
\fId_mydisc\fP Array with the names that th bins should get 
.RE
.PP

.PP
Definition at line 671 of file HistClass\&.hh\&.
.PP
References html_to_bash_ascii_converter::dummy, and histo\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::NameBins (Int_tn_histo, const char *name, const uintn_bins, TString *d_mydisc)\fC [static]\fP"

.PP
Function to give one 1D histogram from the map alphanumeric bin labels\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn_histo\fP Number of the histogram that should get bin names 
.br
\fIname\fP Name of the histogram that should get bin names 
.br
\fIn_bins\fP of bins that should be renamed 
.br
\fId_mydisc\fP Array with the names that th bins should get 
.RE
.PP

.PP
Definition at line 688 of file HistClass\&.hh\&.
.PP
References html_to_bash_ascii_converter::dummy, and histo\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP TH1D* HistClass::ReturnHist (const char *name)\fC [static]\fP"

.PP
Function to get one 1D histogram from the map without number\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the histogram that should be returned 
.br
\fIhisto\fP Returned histogram 
.RE
.PP

.PP
Definition at line 654 of file HistClass\&.hh\&.
.PP
References html_to_bash_ascii_converter::dummy, and histo\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::SetToZero (Int_tn_histo, const char *name)\fC [static]\fP"

.PP
Function to set all negative bin contents to zero for a 1D histogram\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn_histo\fP Number of the histogram that should be modified 
.br
\fIname\fP Name of the histogram that should be modified 
.RE
.PP

.PP
Definition at line 637 of file HistClass\&.hh\&.
.PP
References html_to_bash_ascii_converter::dummy, and histo\&.
.SS "\fBSUPPRESS_NOT_USED_WARN\fP void HistClass::split (const std::string &s, chardelim, std::vector< std::string > &elems)"

.PP
Function split a string at a delimiter\&. Example to create a nice folder structure in your output folder //void specialAna::channel_writer(TFile* file, const char* channel) { //file1->cd(); //file1->mkdir(channel); //for ( int i = 0; i < channel_stages[channel]; i++) { //char n_satge = (char)(((int)'0')+i); //file1->mkdir(TString::Format('%s/Stage_%c', channel, n_satge)); //file1->cd(TString::Format('%s/Stage_%c/', channel, n_satge)); //HistClass\fBWriteAll\fP(TString::Format('_%s_', channel),TString::Format('%s:_%c_', channel, n_satge),TString::Format('sys')); //file1->cd(); //file1->mkdir(TString::Format('%s/Stage_%c/sys', channel, n_satge)); //file1->cd(TString::Format('%s/Stage_%c/sys/', channel, n_satge)); //HistClass\fBWriteAll\fP(TString::Format('_%s_', channel),TString::Format('_%c_:sys', n_satge)); //} //file1->cd(); //}
.PP
This function splits a given string at a given delimineter, and pushes the results in a given vector\&. 
.PP
\fBParameters:\fP
.RS 4
\fI&s\fP String that should be split 
.br
\fIdelim\fP Delimiter where the string should be split 
.br
\fI&elems\fP Vector in which the substrings should be pushed 
.RE
.PP

.PP
Definition at line 408 of file HistClass\&.hh\&.
.PP
Referenced by gridFunctions::getdcachelist(), split(), WriteAll(), and WriteAll2()\&.
.SS "\fBSUPPRESS_NOT_USED_WARN\fP std::vector<std::string> HistClass::split (const std::string &s, chardelim)"

.PP
Function split a string at a delimiter and return the results\&. This function splits a given string at a given delimineter, and returns the resulting substrings as a vector\&. 
.PP
\fBParameters:\fP
.RS 4
\fI&s\fP String that should be split 
.br
\fIdelim\fP Delimiter where the string should be split 
.br
\fIelems\fP Vector in which the substrings were pushed 
.RE
.PP

.PP
Definition at line 424 of file HistClass\&.hh\&.
.PP
References split()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::Write (Int_tn_histo, const char *name)\fC [static]\fP"

.PP
Function to write one 1D histogram of the map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn_histo\fP Number of the histogram that should be written 
.br
\fIname\fP Name of the histogram that should be written 
.RE
.PP

.PP
Definition at line 328 of file HistClass\&.hh\&.
.PP
References html_to_bash_ascii_converter::dummy, and histo\&.
.PP
Referenced by WriteAll(), WriteAll2(), WriteAllTrees(), and WriteN()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::Write (const char *name)\fC [static]\fP"

.PP
Function to write one 1D histogram of the map without number\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the histogram that should be written 
.RE
.PP

.PP
Definition at line 338 of file HistClass\&.hh\&.
.PP
References html_to_bash_ascii_converter::dummy, and histo\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::Write2 (const char *name)\fC [static]\fP"

.PP
Function to write one 2D histogram of the map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the histogram that should be written 
.RE
.PP

.PP
Definition at line 626 of file HistClass\&.hh\&.
.PP
References html_to_bash_ascii_converter::dummy, and histo2\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::WriteAll (const char *name = \fC''\fP)\fC [static]\fP"

.PP
Function to write many 1D histograms of the map\&. This function writes all histograms of the map with the default options, otherwise it writes all histograms that contain the given string in there name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Optional string that all histogram names that should be written contain (DEFAULT = '') 
.RE
.PP

.PP
Definition at line 351 of file HistClass\&.hh\&.
.PP
References histo, and Write()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::WriteAll (const char *name, const char *contains_i)\fC [static]\fP"

.PP
Function to write many 1D histograms which contain specific strings of the map\&. This function writes all histograms of the map with that contain the given string in there name\&. The written histo- grams also have to contain a list of strings that are sepe- rated by a ':'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP String that all histogram names that should be written contain 
.br
\fIcontains_i\fP String that of names (seperated by ':') that the histogram name should contain 
.RE
.PP

.PP
Definition at line 439 of file HistClass\&.hh\&.
.PP
References histo, split(), and Write()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::WriteAll (const char *name, const char *contains_i, const char *vetos_i)\fC [static]\fP"

.PP
Function to write many 1D histograms which (not) contain specific strings of the map\&. This function writes all histograms of the map with that contain the given string in there name\&. The written histo- grams also have to contain a list of strings that are sepe- rated by a ':'\&. In this version also a list of strings that should not be contained in the histogram name can be given\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP String that all histogram names that should be written contain 
.br
\fIcontains_i\fP String that of names (seperated by ':') that the histogram name should contain 
.br
\fIvetos_i\fP String that of names (seperated by ':') that the histogram name should not contain 
.RE
.PP

.PP
Definition at line 505 of file HistClass\&.hh\&.
.PP
References histo, split(), and Write()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::WriteAll2 (const char *name = \fC''\fP)\fC [static]\fP"

.PP
Function to write many 2D histograms of the map\&. This function writes all histograms of the map with the default options, otherwise it writes all histograms that contain the given string in there name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Optional string that all histogram names that should be written contain (DEFAULT = '') 
.RE
.PP

.PP
Definition at line 370 of file HistClass\&.hh\&.
.PP
References histo2, and Write()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::WriteAll2 (const char *name, const char *contains_i)\fC [static]\fP"

.PP
Function to write many 2D histograms which contain specific strings of the map\&. This function writes all histograms of the map with that contain the given string in there name\&. The written histo- grams also have to contain a list of strings that are sepe- rated by a ':'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP String that all histogram names that should be written contain 
.br
\fIcontains_i\fP String that of names (seperated by ':') that the histogram name should contain 
.RE
.PP

.PP
Definition at line 471 of file HistClass\&.hh\&.
.PP
References histo2, split(), and Write()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::WriteAll2 (const char *name, const char *contains_i, const char *vetos_i)\fC [static]\fP"

.PP
Function to write many 2D histograms which (not) contain specific strings of the map\&. This function writes all histograms of the map with that contain the given string in there name\&. The written histo- grams also have to contain a list of strings that are sepe- rated by a ':'\&. In this version also a list of strings that should not be contained in the histogram name can be given\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP String that all histogram names that should be written contain 
.br
\fIcontains_i\fP String that of names (seperated by ':') that the histogram name should contain 
.br
\fIvetos_i\fP String that of names (seperated by ':') that the histogram name should not contain 
.RE
.PP

.PP
Definition at line 547 of file HistClass\&.hh\&.
.PP
References histo2, split(), and Write()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::WriteAllTrees (const char *name = \fC''\fP)\fC [static]\fP"

.PP
Function to write many TTrees and TNtupleDs of the maps\&. This function writes all TTrees and TNtupleDs of the maps with the default options, otherwise it writes all histograms that contain the given string in there name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Optional string that all TTrees or TNtupleDs names that should be written contain (DEFAULT = '') 
.RE
.PP

.PP
Definition at line 585 of file HistClass\&.hh\&.
.PP
References trees, ttupple, and Write()\&.
.SS "static \fBSUPPRESS_NOT_USED_WARN\fP void HistClass::WriteN (const char *name = \fC''\fP)\fC [static]\fP"

.PP
Function to write many TNsparses of the map\&. This function writes all nSparses of the map with the default options, otherwise it writes all histograms that contain the given string in there name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Optional string that all nSparses names that should be written contain (DEFAULT = '') 
.RE
.PP

.PP
Definition at line 610 of file HistClass\&.hh\&.
.PP
References histon, and Write()\&.
.SH "Variable Documentation"
.PP 
.SS "std::map<std::string, TH1D * > HistClass::histo\fC [static]\fP"
Map of a string and a TH1D histogram, for easy 1D histogram handling\&. 
.PP
Definition at line 33 of file HistClass\&.hh\&.
.PP
Referenced by CreateHisto(), CreateHistoUnchangedName(), Fill(), NameBins(), ReturnHist(), SetToZero(), Write(), and WriteAll()\&.
.SS "std::map<std::string, TH2D * > HistClass::histo2\fC [static]\fP"
Map of a string and a TH2D histogram, for easy 2D histogram handling\&. 
.PP
Definition at line 34 of file HistClass\&.hh\&.
.PP
Referenced by CreateHisto(), Fill(), Write2(), and WriteAll2()\&.
.SS "std::map<std::string, THnSparseD * > HistClass::histon\fC [static]\fP"
Map of a string and a THnSparseD histogram, for easy nSparse handling\&. 
.PP
Definition at line 35 of file HistClass\&.hh\&.
.PP
Referenced by CreateNSparse(), FillSparse(), and WriteN()\&.
.SS "std::map<std::string, TTree * > HistClass::trees\fC [static]\fP"
Map of a string and a TTree histogram, for easy tree handling\&. 
.PP
Definition at line 37 of file HistClass\&.hh\&.
.PP
Referenced by CreateTree(), FillTree(), and WriteAllTrees()\&.
.SS "std::map<std::string, TNtupleD * > HistClass::ttupple\fC [static]\fP"
Map of a string and a TNtupleD histogram, for easy Ntuple handling\&. 
.PP
Definition at line 36 of file HistClass\&.hh\&.
.PP
Referenced by CreateTree(), FillTree(), and WriteAllTrees()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
