.TH "lheanalyzer.Process" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lheanalyzer.Process \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file lheanalyzer\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lheanalyzer\&.Process\&.__init__ (self, initstr)"

.PP
Definition at line 48 of file lheanalyzer\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lheanalyzer\&.Process\&.id"

.PP
Definition at line 50 of file lheanalyzer\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
