lheanalyzer.Particle
NAME
lheanalyzer.Particle -
SYNOPSIS
Public Member Functions
def __init__
def getTLorentzVector
Public Attributes
spin
Properties
px = property(lambda self: self.momentum[0])
py = property(lambda self: self.momentum[1])
pz = property(lambda self: self.momentum[2])
energy = property(lambda self: self.momentum[3])
mass = property(lambda self: self.momentum[4])
pt = property(lambda self: (self.px**2+self.py**2)**0.5)
tLorentzVector = property(getTLorentzVector)
eta = property(lambda self: self.tLorentzVector.Eta())
phi = property(lambda self: self.tLorentzVector.Phi())
Detailed Description
Describes a single particle
Definition at line 16 of file lheanalyzer.py.
Constructor & Destructor Documentation
def lheanalyzer.Particle.__init__ (self, initstr)
Constuctor call with line from lhe file
Definition at line 18 of file lheanalyzer.py.
Member Function Documentation
def lheanalyzer.Particle.getTLorentzVector (self)
Returns the ROOT TLorentzVector of the particle
Definition at line 22 of file lheanalyzer.py.
Member Data Documentation
lheanalyzer.Particle.spin
Definition at line 21 of file lheanalyzer.py.
Property Documentation
lheanalyzer.Particle.energy = property(lambda self: self.momentum[3]) [static]
Definition at line 28 of file lheanalyzer.py.
Referenced by lheanalyzer.LorentzVector.add(), and lheanalyzer.LorentzVector.invariantMass().
lheanalyzer.Particle.eta = property(lambda self: self.tLorentzVector.Eta()) [static]
Definition at line 32 of file lheanalyzer.py.
lheanalyzer.Particle.mass = property(lambda self: self.momentum[4]) [static]
Definition at line 29 of file lheanalyzer.py.
lheanalyzer.Particle.phi = property(lambda self: self.tLorentzVector.Phi()) [static]
Definition at line 33 of file lheanalyzer.py.
lheanalyzer.Particle.pt = property(lambda self: (self.px**2+self.py**2)**0.5) [static]
Definition at line 30 of file lheanalyzer.py.
lheanalyzer.Particle.px = property(lambda self: self.momentum[0]) [static]
Definition at line 25 of file lheanalyzer.py.
Referenced by lheanalyzer.LorentzVector.add(), and lheanalyzer.LorentzVector.invariantMass().
lheanalyzer.Particle.py = property(lambda self: self.momentum[1]) [static]
Definition at line 26 of file lheanalyzer.py.
Referenced by lheanalyzer.LorentzVector.add(), and lheanalyzer.LorentzVector.invariantMass().
lheanalyzer.Particle.pz = property(lambda self: self.momentum[2]) [static]
Definition at line 27 of file lheanalyzer.py.
Referenced by lheanalyzer.LorentzVector.add(), and lheanalyzer.LorentzVector.invariantMass().
lheanalyzer.Particle.tLorentzVector = property(getTLorentzVector) [static]
Definition at line 31 of file lheanalyzer.py.
Author
Generated automatically by Doxygen for libs3a from the source code.