.TH "mergeFolders" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mergeFolders \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.ti -1c
.RI "def \fBmultiextractRoot\fP"
.br
.ti -1c
.RI "def \fBextractRootFiles\fP"
.br
.ti -1c
.RI "def \fBmegeRootFiles\fP"
.br
.ti -1c
.RI "def \fBhadd\fP"
.br
.ti -1c
.RI "def \fBcleanUp\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBlog\fP = logging\&.getLogger( 'merger' )"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def mergeFolders\&.cleanUp (options)"

.PP
Definition at line 149 of file mergeFolders\&.py\&.
.PP
References main()\&.
.PP
Referenced by main()\&.
.SS "def mergeFolders\&.extractRootFiles (options)"

.PP
Definition at line 59 of file mergeFolders\&.py\&.
.PP
Referenced by main()\&.
.SS "def mergeFolders\&.hadd (item)"

.PP
Definition at line 130 of file mergeFolders\&.py\&.
.SS "def mergeFolders\&.main ()"

.PP
Definition at line 18 of file mergeFolders\&.py\&.
.PP
References cleanUp(), extractRootFiles(), and megeRootFiles()\&.
.PP
Referenced by cleanUp()\&.
.SS "def mergeFolders\&.megeRootFiles (options)"

.PP
Definition at line 89 of file mergeFolders\&.py\&.
.PP
Referenced by main()\&.
.SS "def mergeFolders\&.multiextractRoot (splited)"

.PP
Definition at line 46 of file mergeFolders\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "tuple mergeFolders\&.log = logging\&.getLogger( 'merger' )"

.PP
Definition at line 5 of file mergeFolders\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
