.TH "python/multiLogging.py" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/multiLogging.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmultiLogging\&.SubProcessLogHandler\fP"
.br
.ti -1c
.RI "class \fBmultiLogging\&.LogQueueReader\fP"
.br
.ti -1c
.RI "class \fBmultiLogging\&.LoggingProcess\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBmultiLogging\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
