.TH "multiLogging.LoggingProcess" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiLogging.LoggingProcess \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Process\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBrun\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBqueue\fP"
.br
.ti -1c
.RI "\fBlogger\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "def \fB_setupLogger\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file multiLogging\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def multiLogging\&.LoggingProcess\&.__init__ (self, queue)"

.PP
Definition at line 70 of file multiLogging\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def multiLogging\&.LoggingProcess\&._setupLogger (self)\fC [private]\fP"

.PP
Definition at line 74 of file multiLogging\&.py\&.
.PP
References multiLogging\&.SubProcessLogHandler\&.queue, multiLogging\&.LogQueueReader\&.queue, multiLogging\&.LoggingProcess\&.queue, and curseshelpers\&.CursesMultiHandler\&.queue\&.
.PP
Referenced by multiLogging\&.LoggingProcess\&.run()\&.
.SS "def multiLogging\&.LoggingProcess\&.run (self)"

.PP
Definition at line 96 of file multiLogging\&.py\&.
.PP
References multiLogging\&.LoggingProcess\&._setupLogger(), crabFunctions\&.CrabController\&.logger, and multiLogging\&.LoggingProcess\&.logger\&.
.SH "Member Data Documentation"
.PP 
.SS "multiLogging\&.LoggingProcess\&.logger"

.PP
Definition at line 94 of file multiLogging\&.py\&.
.PP
Referenced by multiLogging\&.LoggingProcess\&.run()\&.
.SS "multiLogging\&.LoggingProcess\&.queue"

.PP
Definition at line 72 of file multiLogging\&.py\&.
.PP
Referenced by multiLogging\&.LoggingProcess\&._setupLogger()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
