.TH "multiLogging.SubProcessLogHandler" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiLogging.SubProcessLogHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Handler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBemit\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBqueue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
handler used by subprocesses

It simply puts items on a Queue for the main process to log.
.fi
.PP
 
.PP
Definition at line 17 of file multiLogging\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def multiLogging\&.SubProcessLogHandler\&.__init__ (self, queue)"

.PP
Definition at line 24 of file multiLogging\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def multiLogging\&.SubProcessLogHandler\&.emit (self, record)"

.PP
Definition at line 28 of file multiLogging\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "multiLogging\&.SubProcessLogHandler\&.queue"

.PP
Definition at line 26 of file multiLogging\&.py\&.
.PP
Referenced by multiLogging\&.LoggingProcess\&._setupLogger()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
