.TH "submit" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
submit \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBlogger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def submit\&.main ()"

.PP
Definition at line 12 of file submit\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "tuple submit\&.logger = logging\&.getLogger(__name__)"

.PP
Definition at line 9 of file submit\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
