.TH "terminalFunctions.bcolors" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
terminalFunctions.bcolors \- 
.PP
Color definition for terminal output\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBdisable\fP"
.br
.RI "\fIFunction to unset all colors\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHEADER\fP"
.br
.ti -1c
.RI "\fBOKBLUE\fP"
.br
.ti -1c
.RI "\fBOKGREEN\fP"
.br
.ti -1c
.RI "\fBWARNING\fP"
.br
.ti -1c
.RI "\fBFAIL\fP"
.br
.ti -1c
.RI "\fBCYAN\fP"
.br
.ti -1c
.RI "\fBWHITE\fP"
.br
.ti -1c
.RI "\fBENDC\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBHEADER\fP = '\\033[35m'"
.br
.ti -1c
.RI "string \fBOKBLUE\fP = '\\033[34m'"
.br
.ti -1c
.RI "string \fBOKGREEN\fP = '\\033[32m'"
.br
.ti -1c
.RI "string \fBWARNING\fP = '\\033[33m'"
.br
.ti -1c
.RI "string \fBFAIL\fP = '\\033[31m'"
.br
.ti -1c
.RI "string \fBCYAN\fP = '\\033[36m'"
.br
.ti -1c
.RI "string \fBWHITE\fP = '\\033[37m'"
.br
.ti -1c
.RI "string \fBENDC\fP = '\\033[0m'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Color definition for terminal output\&. 
.PP
Definition at line 10 of file terminalFunctions\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def terminalFunctions\&.bcolors\&.disable (self)"

.PP
Function to unset all colors\&. 
.PP
Definition at line 21 of file terminalFunctions\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "string terminalFunctions\&.bcolors\&.CYAN = '\\033[36m'\fC [static]\fP"

.PP
Definition at line 16 of file terminalFunctions\&.py\&.
.SS "terminalFunctions\&.bcolors\&.CYAN"

.PP
Definition at line 27 of file terminalFunctions\&.py\&.
.SS "string terminalFunctions\&.bcolors\&.ENDC = '\\033[0m'\fC [static]\fP"

.PP
Definition at line 18 of file terminalFunctions\&.py\&.
.SS "terminalFunctions\&.bcolors\&.ENDC"

.PP
Definition at line 29 of file terminalFunctions\&.py\&.
.SS "string terminalFunctions\&.bcolors\&.FAIL = '\\033[31m'\fC [static]\fP"

.PP
Definition at line 15 of file terminalFunctions\&.py\&.
.SS "terminalFunctions\&.bcolors\&.FAIL"

.PP
Definition at line 26 of file terminalFunctions\&.py\&.
.SS "string terminalFunctions\&.bcolors\&.HEADER = '\\033[35m'\fC [static]\fP"

.PP
Definition at line 11 of file terminalFunctions\&.py\&.
.SS "terminalFunctions\&.bcolors\&.HEADER"

.PP
Definition at line 22 of file terminalFunctions\&.py\&.
.SS "string terminalFunctions\&.bcolors\&.OKBLUE = '\\033[34m'\fC [static]\fP"

.PP
Definition at line 12 of file terminalFunctions\&.py\&.
.SS "terminalFunctions\&.bcolors\&.OKBLUE"

.PP
Definition at line 23 of file terminalFunctions\&.py\&.
.SS "string terminalFunctions\&.bcolors\&.OKGREEN = '\\033[32m'\fC [static]\fP"

.PP
Definition at line 13 of file terminalFunctions\&.py\&.
.SS "terminalFunctions\&.bcolors\&.OKGREEN"

.PP
Definition at line 24 of file terminalFunctions\&.py\&.
.SS "string terminalFunctions\&.bcolors\&.WARNING = '\\033[33m'\fC [static]\fP"

.PP
Definition at line 14 of file terminalFunctions\&.py\&.
.SS "terminalFunctions\&.bcolors\&.WARNING"

.PP
Definition at line 25 of file terminalFunctions\&.py\&.
.SS "string terminalFunctions\&.bcolors\&.WHITE = '\\033[37m'\fC [static]\fP"

.PP
Definition at line 17 of file terminalFunctions\&.py\&.
.SS "terminalFunctions\&.bcolors\&.WHITE"

.PP
Definition at line 28 of file terminalFunctions\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
