.TH "test_logging_lib.LoggerTester" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_logging_lib.LoggerTester \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBtestFunc\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlogger\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file test_logging_lib\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def test_logging_lib\&.LoggerTester\&.__init__ (self, logger = \fCNone\fP)"

.PP
Definition at line 5 of file test_logging_lib\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_logging_lib\&.LoggerTester\&.testFunc (self)"

.PP
Definition at line 34 of file test_logging_lib\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "test_logging_lib\&.LoggerTester\&.logger"

.PP
Definition at line 8 of file test_logging_lib\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
