test_logging_App
NAME
test_logging_App -
SYNOPSIS
Variables
AppWithOwnLogger = False
string COMMENT_CHAR = '#'
list log_choices = [ 'ERROR', 'WARNING', 'INFO', 'DEBUG' ]
string date = '%F %H:%M:%S'
tuple log = logging.getLogger( 'logging_test' )
string format = '%(levelname)s (%(name)s) [%(asctime)s]: %(message)s'
tuple formatter = logging.Formatter( format )
string log_file_name = 'logging_test.log'
tuple hdlr = logging.FileHandler( log_file_name, mode='w' )
tuple myTester = LoggerTester(logger = log)
Variable Documentation
test_logging_App.AppWithOwnLogger = False
Definition at line 5 of file test_logging_App.py.
string test_logging_App.COMMENT_CHAR = '#'
Definition at line 9 of file test_logging_App.py.
string test_logging_App.date = '%F %H:%M:%S'
Definition at line 11 of file test_logging_App.py.
string test_logging_App.format = '%(levelname)s (%(name)s) [%(asctime)s]: %(message)s'
Definition at line 17 of file test_logging_App.py.
Referenced by curseshelpers.SelectTable._drawColHeaders(), curseshelpers.SelectTable._drawFooters(), curseshelpers.MultiText._redraw(), curseshelpers.TabbedText._redrawHeading(), curseshelpers.SelectTable._redrawRows(), rounding.rounding.htmlValue(), rounding.rounding.htmlValueError(), rounding.rounding.htmlValueUpDownError(), rounding.rounding.latexValue(), rounding.rounding.latexValueError(), rounding.rounding.latexValueUpDownError(), rounding.rounding.sdr(), and terminalFunctions.update_progress().
tuple test_logging_App.formatter = logging.Formatter( format )
Definition at line 19 of file test_logging_App.py.
tuple test_logging_App.hdlr = logging.FileHandler( log_file_name, mode='w' )
Definition at line 21 of file test_logging_App.py.
tuple test_logging_App.log = logging.getLogger( 'logging_test' )
Definition at line 14 of file test_logging_App.py.
list test_logging_App.log_choices = [ 'ERROR', 'WARNING', 'INFO', 'DEBUG' ]
Definition at line 10 of file test_logging_App.py.
string test_logging_App.log_file_name = 'logging_test.log'
Definition at line 20 of file test_logging_App.py.
tuple test_logging_App.myTester = LoggerTester(logger = log)
Definition at line 26 of file test_logging_App.py.
Author
Generated automatically by Doxygen for libs3a from the source code.