.TH "python/test_logging_App.py" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/test_logging_App.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBtest_logging_App\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtest_logging_App\&.AppWithOwnLogger\fP = False"
.br
.ti -1c
.RI "string \fBtest_logging_App\&.COMMENT_CHAR\fP = '#'"
.br
.ti -1c
.RI "list \fBtest_logging_App\&.log_choices\fP = [ 'ERROR', 'WARNING', 'INFO', 'DEBUG' ]"
.br
.ti -1c
.RI "string \fBtest_logging_App\&.date\fP = '%F %H:%M:%S'"
.br
.ti -1c
.RI "tuple \fBtest_logging_App\&.log\fP = logging\&.getLogger( 'logging_test' )"
.br
.ti -1c
.RI "string \fBtest_logging_App\&.format\fP = '%(levelname)s (%(name)s) [%(asctime)s]: %(message)s'"
.br
.ti -1c
.RI "tuple \fBtest_logging_App\&.formatter\fP = logging\&.Formatter( format )"
.br
.ti -1c
.RI "string \fBtest_logging_App\&.log_file_name\fP = 'logging_test\&.log'"
.br
.ti -1c
.RI "tuple \fBtest_logging_App\&.hdlr\fP = logging\&.FileHandler( log_file_name, mode='w' )"
.br
.ti -1c
.RI "tuple \fBtest_logging_App\&.myTester\fP = LoggerTester(logger = log)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
