.TH "examples/lheanalyzer/wprime.py" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/lheanalyzer/wprime.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBwprime\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBwprime\&.parser\fP = optparse\&.OptionParser( description='LHE Analysis\&.', usage='usage: %prog files')"
.br
.ti -1c
.RI "tuple \fBwprime\&.hTransverseMassAll\fP = ROOT\&.TH1F('hTransverseMassAll','',400,0,8000)"
.br
.ti -1c
.RI "tuple \fBwprime\&.hInvariantMassAll\fP = ROOT\&.TH1F('hInvariantMassAll','',400,0,8000)"
.br
.ti -1c
.RI "tuple \fBwprime\&.analysis\fP = \fBlheanalyzer\&.LHEAnalysis\fP(filename)"
.br
.ti -1c
.RI "tuple \fBwprime\&.hTransverseMass\fP = ROOT\&.TH1F('hTransverseMass','',400,0,8000)"
.br
.ti -1c
.RI "tuple \fBwprime\&.hInvariantMass\fP = ROOT\&.TH1F('hInvariantMass','',400,0,8000)"
.br
.ti -1c
.RI "tuple \fBwprime\&.charged\fP = filter(lambda particle: particle\&.pdgId in [-15,-13,-11,11,13,15], event\&.particles)"
.br
.ti -1c
.RI "tuple \fBwprime\&.neutrino\fP = filter(lambda particle: particle\&.pdgId in [-16,-14,-12,12,14,16], event\&.particles)"
.br
.ti -1c
.RI "tuple \fBwprime\&.mass\fP = \fBlheanalyzer\&.invariantMass\fP(charged[0],neutrino[0])"
.br
.ti -1c
.RI "tuple \fBwprime\&.transverseMass\fP = lheanalyzer\&.transverseMass(charged[0],neutrino[0])"
.br
.ti -1c
.RI "\fBwprime\&.crossSection\fP = analysis\&.totalCrossSection"
.br
.ti -1c
.RI "tuple \fBwprime\&.outfile\fP = ROOT\&.TFile('outfile_lheanalyzer\&.root' ,'RECREATE')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
