.TH "wprime" 3 "Tue Jan 20 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wprime \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBparser\fP = optparse\&.OptionParser( description='LHE Analysis\&.', usage='usage: %prog files')"
.br
.ti -1c
.RI "tuple \fBhTransverseMassAll\fP = ROOT\&.TH1F('hTransverseMassAll','',400,0,8000)"
.br
.ti -1c
.RI "tuple \fBhInvariantMassAll\fP = ROOT\&.TH1F('hInvariantMassAll','',400,0,8000)"
.br
.ti -1c
.RI "tuple \fBanalysis\fP = \fBlheanalyzer\&.LHEAnalysis\fP(filename)"
.br
.ti -1c
.RI "tuple \fBhTransverseMass\fP = ROOT\&.TH1F('hTransverseMass','',400,0,8000)"
.br
.ti -1c
.RI "tuple \fBhInvariantMass\fP = ROOT\&.TH1F('hInvariantMass','',400,0,8000)"
.br
.ti -1c
.RI "tuple \fBcharged\fP = filter(lambda particle: particle\&.pdgId in [-15,-13,-11,11,13,15], event\&.particles)"
.br
.ti -1c
.RI "tuple \fBneutrino\fP = filter(lambda particle: particle\&.pdgId in [-16,-14,-12,12,14,16], event\&.particles)"
.br
.ti -1c
.RI "tuple \fBmass\fP = \fBlheanalyzer\&.invariantMass\fP(\fBcharged\fP[0],\fBneutrino\fP[0])"
.br
.ti -1c
.RI "tuple \fBtransverseMass\fP = lheanalyzer\&.transverseMass(\fBcharged\fP[0],\fBneutrino\fP[0])"
.br
.ti -1c
.RI "\fBcrossSection\fP = analysis\&.totalCrossSection"
.br
.ti -1c
.RI "tuple \fBoutfile\fP = ROOT\&.TFile('outfile_lheanalyzer\&.root' ,'RECREATE')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple wprime\&.analysis = \fBlheanalyzer\&.LHEAnalysis\fP(filename)"

.PP
Definition at line 22 of file wprime\&.py\&.
.SS "tuple wprime\&.charged = filter(lambda particle: particle\&.pdgId in [-15,-13,-11,11,13,15], event\&.particles)"

.PP
Definition at line 36 of file wprime\&.py\&.
.SS "wprime\&.crossSection = analysis\&.totalCrossSection"

.PP
Definition at line 58 of file wprime\&.py\&.
.SS "tuple wprime\&.hInvariantMass = ROOT\&.TH1F('hInvariantMass','',400,0,8000)"

.PP
Definition at line 26 of file wprime\&.py\&.
.SS "tuple wprime\&.hInvariantMassAll = ROOT\&.TH1F('hInvariantMassAll','',400,0,8000)"

.PP
Definition at line 20 of file wprime\&.py\&.
.SS "tuple wprime\&.hTransverseMass = ROOT\&.TH1F('hTransverseMass','',400,0,8000)"

.PP
Definition at line 25 of file wprime\&.py\&.
.SS "tuple wprime\&.hTransverseMassAll = ROOT\&.TH1F('hTransverseMassAll','',400,0,8000)"

.PP
Definition at line 19 of file wprime\&.py\&.
.SS "tuple wprime\&.mass = \fBlheanalyzer\&.invariantMass\fP(\fBcharged\fP[0],\fBneutrino\fP[0])"

.PP
Definition at line 46 of file wprime\&.py\&.
.SS "tuple wprime\&.neutrino = filter(lambda particle: particle\&.pdgId in [-16,-14,-12,12,14,16], event\&.particles)"

.PP
Definition at line 41 of file wprime\&.py\&.
.SS "tuple wprime\&.outfile = ROOT\&.TFile('outfile_lheanalyzer\&.root' ,'RECREATE')"

.PP
Definition at line 70 of file wprime\&.py\&.
.SS "tuple wprime\&.parser = optparse\&.OptionParser( description='LHE Analysis\&.', usage='usage: %prog files')"

.PP
Definition at line 16 of file wprime\&.py\&.
.SS "tuple wprime\&.transverseMass = lheanalyzer\&.transverseMass(\fBcharged\fP[0],\fBneutrino\fP[0])"

.PP
Definition at line 47 of file wprime\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
