.TH "aix3adb.MCSample" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aix3adb.MCSample \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaix3adb\&.Aix3adbBaseElement\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 30 of file aix3adb\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
