.TH "crabFunctions" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crabFunctions \- 
.PP
This module provides common functions for tasks with crab3\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCrabController\fP"
.br
.RI "\fIThe \fBCrabController\fP class\&. \fP"
.ti -1c
.RI "class \fBCrabTask\fP"
.br
.RI "\fIClass for a single CrabRequest\&. \fP"
.ti -1c
.RI "class \fBTaskStats\fP"
.br
.RI "\fIClass holds job statistics for several Crab tasks\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This module provides common functions for tasks with crab3\&. 

This module provides common functions for tasks with crab3\&. You need no create a \fBCrabController\fP object in order to use the functions 
.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
