.TH "curseshelpers.MultiText" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curseshelpers.MultiText \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcurseshelpers\&.BaseElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBclear\fP"
.br
.ti -1c
.RI "def \fBaddFile\fP"
.br
.ti -1c
.RI "def \fBaddText\fP"
.br
.ti -1c
.RI "def \fBrefresh\fP"
.br
.ti -1c
.RI "def \fBgoUp\fP"
.br
.ti -1c
.RI "def \fBgoDown\fP"
.br
.ti -1c
.RI "def \fBpageUp\fP"
.br
.ti -1c
.RI "def \fBpageDown\fP"
.br
.ti -1c
.RI "def \fBhome\fP"
.br
.ti -1c
.RI "def \fBend\fP"
.br
.ti -1c
.RI "def \fBheight\fP"
.br
.ti -1c
.RI "def \fBwidth\fP"
.br
.ti -1c
.RI "def \fBgoLeft\fP"
.br
.ti -1c
.RI "def \fBgoRight\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBparent\fP"
.br
.ti -1c
.RI "\fBleft\fP"
.br
.ti -1c
.RI "\fBpad\fP"
.br
.ti -1c
.RI "\fBposition\fP"
.br
.ti -1c
.RI "\fBtext\fP"
.br
.ti -1c
.RI "\fBnrows\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "def \fB_redraw\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_height\fP"
.br
.ti -1c
.RI "\fB_width\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 178 of file curseshelpers\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def curseshelpers\&.MultiText\&.__init__ (self, screen, maxrows = \fC20000\fP, top = \fC1\fP, left = \fC0\fP, height = \fCNone\fP, width = \fCNone\fP)"

.PP
Definition at line 179 of file curseshelpers\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def curseshelpers\&.MultiText\&._redraw (self)\fC [private]\fP"

.PP
Definition at line 208 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.chunks(), curseshelpers\&.MultiText\&.nrows, curseshelpers\&.TabbedText\&.text, curseshelpers\&.BottomText\&.text, curseshelpers\&.MultiText\&.text, curseshelpers\&.TabbedText\&.width(), curseshelpers\&.BottomText\&.width(), rootplotlib\&.Legend\&.width, and curseshelpers\&.MultiText\&.width()\&.
.PP
Referenced by curseshelpers\&.MultiText\&.addText(), and curseshelpers\&.Text\&.setText()\&.
.SS "def curseshelpers\&.MultiText\&.addFile (self, title, filename)"

.PP
Definition at line 191 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&.addText(), curseshelpers\&.BottomText\&.addText(), and curseshelpers\&.MultiText\&.addText()\&.
.SS "def curseshelpers\&.MultiText\&.addText (self, title, text)"

.PP
Definition at line 195 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&._redraw(), curseshelpers\&.BottomText\&._redraw(), and curseshelpers\&.MultiText\&._redraw()\&.
.PP
Referenced by curseshelpers\&.MultiText\&.addFile()\&.
.SS "def curseshelpers\&.MultiText\&.clear (self)"

.PP
Definition at line 188 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&.text, curseshelpers\&.BottomText\&.text, and curseshelpers\&.MultiText\&.text\&.
.SS "def curseshelpers\&.MultiText\&.end (self)"

.PP
Definition at line 227 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&.height(), curseshelpers\&.BottomText\&.height(), rootplotlib\&.Legend\&.height, curseshelpers\&.MultiText\&.height(), curseshelpers\&.MultiText\&.nrows, and curseshelpers\&.MultiText\&.position\&.
.SS "def curseshelpers\&.MultiText\&.goDown (self)"

.PP
Definition at line 202 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&.height(), curseshelpers\&.BottomText\&.height(), rootplotlib\&.Legend\&.height, curseshelpers\&.MultiText\&.height(), curseshelpers\&.MultiText\&.nrows, and curseshelpers\&.MultiText\&.position\&.
.SS "def curseshelpers\&.BaseElement\&.goLeft (self)\fC [inherited]\fP"

.PP
Definition at line 29 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.goRight (self)\fC [inherited]\fP"

.PP
Definition at line 31 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.MultiText\&.goUp (self)"

.PP
Definition at line 200 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.MultiText\&.position\&.
.SS "def curseshelpers\&.MultiText\&.height (self)"

.PP
Definition at line 230 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&._height, curseshelpers\&.BottomText\&._height, and curseshelpers\&.MultiText\&._height\&.
.PP
Referenced by curseshelpers\&.MultiText\&.end(), curseshelpers\&.Text\&.end(), curseshelpers\&.SelectTable\&.end(), curseshelpers\&.MultiText\&.goDown(), curseshelpers\&.Text\&.goDown(), curseshelpers\&.SelectTable\&.goDown(), curseshelpers\&.MultiText\&.pageDown(), curseshelpers\&.Text\&.pageDown(), curseshelpers\&.SelectTable\&.pageDown(), curseshelpers\&.MultiText\&.pageUp(), curseshelpers\&.Text\&.pageUp(), curseshelpers\&.SelectTable\&.pageUp(), curseshelpers\&.MultiText\&.refresh(), curseshelpers\&.Text\&.refresh(), and curseshelpers\&.SelectTable\&.refresh()\&.
.SS "def curseshelpers\&.MultiText\&.home (self)"

.PP
Definition at line 225 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.MultiText\&.position\&.
.SS "def curseshelpers\&.MultiText\&.pageDown (self)"

.PP
Definition at line 206 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&.height(), curseshelpers\&.BottomText\&.height(), rootplotlib\&.Legend\&.height, curseshelpers\&.MultiText\&.height(), curseshelpers\&.MultiText\&.nrows, and curseshelpers\&.MultiText\&.position\&.
.SS "def curseshelpers\&.MultiText\&.pageUp (self)"

.PP
Definition at line 204 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&.height(), curseshelpers\&.BottomText\&.height(), rootplotlib\&.Legend\&.height, curseshelpers\&.MultiText\&.height(), and curseshelpers\&.MultiText\&.position\&.
.SS "def curseshelpers\&.MultiText\&.refresh (self)"

.PP
Definition at line 198 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&.height(), curseshelpers\&.BottomText\&.height(), rootplotlib\&.Legend\&.height, curseshelpers\&.MultiText\&.height(), curseshelpers\&.TabbedText\&.left, curseshelpers\&.BottomText\&.left, curseshelpers\&.MultiText\&.left, curseshelpers\&.MultiText\&.position, curseshelpers\&.TabbedText\&.width(), curseshelpers\&.BottomText\&.width(), rootplotlib\&.Legend\&.width, and curseshelpers\&.MultiText\&.width()\&.
.SS "def curseshelpers\&.MultiText\&.width (self)"

.PP
Definition at line 233 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&._width, curseshelpers\&.BottomText\&._width, and curseshelpers\&.MultiText\&._width\&.
.PP
Referenced by curseshelpers\&.SelectTable\&._drawColHeaders(), curseshelpers\&.MultiText\&._redraw(), curseshelpers\&.Text\&._redraw(), curseshelpers\&.SelectTable\&._redrawRows(), curseshelpers\&.MultiText\&.refresh(), curseshelpers\&.Text\&.refresh(), and curseshelpers\&.SelectTable\&.refresh()\&.
.SH "Member Data Documentation"
.PP 
.SS "curseshelpers\&.MultiText\&._height\fC [private]\fP"

.PP
Definition at line 182 of file curseshelpers\&.py\&.
.PP
Referenced by curseshelpers\&.MultiText\&.height(), curseshelpers\&.Text\&.height(), and curseshelpers\&.SelectTable\&.height()\&.
.SS "curseshelpers\&.MultiText\&._width\fC [private]\fP"

.PP
Definition at line 183 of file curseshelpers\&.py\&.
.PP
Referenced by curseshelpers\&.MultiText\&.width(), curseshelpers\&.Text\&.width(), and curseshelpers\&.SelectTable\&.width()\&.
.SS "curseshelpers\&.MultiText\&.left"

.PP
Definition at line 181 of file curseshelpers\&.py\&.
.PP
Referenced by curseshelpers\&.MultiText\&.refresh(), curseshelpers\&.Text\&.refresh(), and curseshelpers\&.SelectTable\&.refresh()\&.
.SS "curseshelpers\&.MultiText\&.nrows"

.PP
Definition at line 187 of file curseshelpers\&.py\&.
.PP
Referenced by curseshelpers\&.MultiText\&._redraw(), curseshelpers\&.Text\&._redraw(), curseshelpers\&.SelectTable\&.addRow(), curseshelpers\&.TabbedText\&.end(), curseshelpers\&.MultiText\&.end(), curseshelpers\&.Text\&.end(), curseshelpers\&.SelectTable\&.end(), curseshelpers\&.TabbedText\&.goDown(), curseshelpers\&.MultiText\&.goDown(), curseshelpers\&.Text\&.goDown(), curseshelpers\&.SelectTable\&.goDown(), curseshelpers\&.TabbedText\&.pageDown(), curseshelpers\&.MultiText\&.pageDown(), curseshelpers\&.Text\&.pageDown(), and curseshelpers\&.SelectTable\&.pageDown()\&.
.SS "curseshelpers\&.MultiText\&.pad"

.PP
Definition at line 184 of file curseshelpers\&.py\&.
.SS "curseshelpers\&.MultiText\&.parent"

.PP
Definition at line 180 of file curseshelpers\&.py\&.
.SS "curseshelpers\&.MultiText\&.position"

.PP
Definition at line 185 of file curseshelpers\&.py\&.
.PP
Referenced by curseshelpers\&.MultiText\&.end(), curseshelpers\&.Text\&.end(), curseshelpers\&.SelectTable\&.end(), curseshelpers\&.MultiText\&.goDown(), curseshelpers\&.Text\&.goDown(), curseshelpers\&.SelectTable\&.goDown(), curseshelpers\&.MultiText\&.goUp(), curseshelpers\&.Text\&.goUp(), curseshelpers\&.MultiText\&.home(), curseshelpers\&.Text\&.home(), curseshelpers\&.SelectTable\&.home(), curseshelpers\&.MultiText\&.pageDown(), curseshelpers\&.Text\&.pageDown(), curseshelpers\&.SelectTable\&.pageDown(), curseshelpers\&.MultiText\&.pageUp(), curseshelpers\&.Text\&.pageUp(), curseshelpers\&.SelectTable\&.pageUp(), curseshelpers\&.MultiText\&.refresh(), curseshelpers\&.Text\&.refresh(), and curseshelpers\&.SelectTable\&.refresh()\&.
.SS "curseshelpers\&.MultiText\&.text"

.PP
Definition at line 186 of file curseshelpers\&.py\&.
.PP
Referenced by curseshelpers\&.MultiText\&._redraw(), curseshelpers\&.MultiText\&.clear(), and curseshelpers\&.Text\&.setText()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
