.TH "curseshelpers.BottomText" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curseshelpers.BottomText \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcurseshelpers\&.BaseElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBclear\fP"
.br
.ti -1c
.RI "def \fBaddText\fP"
.br
.ti -1c
.RI "def \fBrefresh\fP"
.br
.ti -1c
.RI "def \fBheight\fP"
.br
.ti -1c
.RI "def \fBwidth\fP"
.br
.ti -1c
.RI "def \fBgoLeft\fP"
.br
.ti -1c
.RI "def \fBgoRight\fP"
.br
.ti -1c
.RI "def \fBgoUp\fP"
.br
.ti -1c
.RI "def \fBgoDown\fP"
.br
.ti -1c
.RI "def \fBpageUp\fP"
.br
.ti -1c
.RI "def \fBpageDown\fP"
.br
.ti -1c
.RI "def \fBhome\fP"
.br
.ti -1c
.RI "def \fBend\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBparent\fP"
.br
.ti -1c
.RI "\fBleft\fP"
.br
.ti -1c
.RI "\fBpad\fP"
.br
.ti -1c
.RI "\fBtext\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "def \fB_redraw\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_height\fP"
.br
.ti -1c
.RI "\fB_width\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 139 of file curseshelpers\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def curseshelpers\&.BottomText\&.__init__ (self, screen, top = \fC1\fP, left = \fC0\fP, height = \fCNone\fP, width = \fCNone\fP)"

.PP
Definition at line 140 of file curseshelpers\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def curseshelpers\&.BottomText\&._redraw (self)\fC [private]\fP"

.PP
Definition at line 156 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.chunks(), curseshelpers\&.TabbedText\&.height(), curseshelpers\&.BottomText\&.height(), rootplotlib\&.Legend\&.height, curseshelpers\&.TabbedText\&.text, curseshelpers\&.BottomText\&.text, curseshelpers\&.TabbedText\&.width(), curseshelpers\&.BottomText\&.width(), and rootplotlib\&.Legend\&.width\&.
.PP
Referenced by curseshelpers\&.BottomText\&.addText(), curseshelpers\&.MultiText\&.addText(), and curseshelpers\&.Text\&.setText()\&.
.SS "def curseshelpers\&.BottomText\&.addText (self, text)"

.PP
Definition at line 150 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&._redraw(), curseshelpers\&.BottomText\&._redraw(), curseshelpers\&.TabbedText\&.text, and curseshelpers\&.BottomText\&.text\&.
.PP
Referenced by curseshelpers\&.MultiText\&.addFile()\&.
.SS "def curseshelpers\&.BottomText\&.clear (self)"

.PP
Definition at line 147 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&.text, and curseshelpers\&.BottomText\&.text\&.
.SS "def curseshelpers\&.BaseElement\&.end (self)\fC [inherited]\fP"

.PP
Definition at line 43 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.goDown (self)\fC [inherited]\fP"

.PP
Definition at line 35 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.goLeft (self)\fC [inherited]\fP"

.PP
Definition at line 29 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.goRight (self)\fC [inherited]\fP"

.PP
Definition at line 31 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.goUp (self)\fC [inherited]\fP"

.PP
Definition at line 33 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BottomText\&.height (self)"

.PP
Definition at line 172 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&._height, and curseshelpers\&.BottomText\&._height\&.
.PP
Referenced by curseshelpers\&.BottomText\&._redraw(), curseshelpers\&.MultiText\&.end(), curseshelpers\&.Text\&.end(), curseshelpers\&.SelectTable\&.end(), curseshelpers\&.MultiText\&.goDown(), curseshelpers\&.Text\&.goDown(), curseshelpers\&.SelectTable\&.goDown(), curseshelpers\&.MultiText\&.pageDown(), curseshelpers\&.Text\&.pageDown(), curseshelpers\&.SelectTable\&.pageDown(), curseshelpers\&.MultiText\&.pageUp(), curseshelpers\&.Text\&.pageUp(), curseshelpers\&.SelectTable\&.pageUp(), curseshelpers\&.MultiText\&.refresh(), curseshelpers\&.Text\&.refresh(), and curseshelpers\&.SelectTable\&.refresh()\&.
.SS "def curseshelpers\&.BaseElement\&.home (self)\fC [inherited]\fP"

.PP
Definition at line 41 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.pageDown (self)\fC [inherited]\fP"

.PP
Definition at line 39 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.pageUp (self)\fC [inherited]\fP"

.PP
Definition at line 37 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BottomText\&.refresh (self)"

.PP
Definition at line 154 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BottomText\&.width (self)"

.PP
Definition at line 175 of file curseshelpers\&.py\&.
.PP
References curseshelpers\&.TabbedText\&._width, and curseshelpers\&.BottomText\&._width\&.
.PP
Referenced by curseshelpers\&.SelectTable\&._drawColHeaders(), curseshelpers\&.BottomText\&._redraw(), curseshelpers\&.MultiText\&._redraw(), curseshelpers\&.Text\&._redraw(), curseshelpers\&.SelectTable\&._redrawRows(), curseshelpers\&.MultiText\&.refresh(), curseshelpers\&.Text\&.refresh(), and curseshelpers\&.SelectTable\&.refresh()\&.
.SH "Member Data Documentation"
.PP 
.SS "curseshelpers\&.BottomText\&._height\fC [private]\fP"

.PP
Definition at line 143 of file curseshelpers\&.py\&.
.PP
Referenced by curseshelpers\&.BottomText\&.height(), curseshelpers\&.MultiText\&.height(), curseshelpers\&.Text\&.height(), and curseshelpers\&.SelectTable\&.height()\&.
.SS "curseshelpers\&.BottomText\&._width\fC [private]\fP"

.PP
Definition at line 144 of file curseshelpers\&.py\&.
.PP
Referenced by curseshelpers\&.BottomText\&.width(), curseshelpers\&.MultiText\&.width(), curseshelpers\&.Text\&.width(), and curseshelpers\&.SelectTable\&.width()\&.
.SS "curseshelpers\&.BottomText\&.left"

.PP
Definition at line 142 of file curseshelpers\&.py\&.
.PP
Referenced by curseshelpers\&.MultiText\&.refresh(), curseshelpers\&.Text\&.refresh(), and curseshelpers\&.SelectTable\&.refresh()\&.
.SS "curseshelpers\&.BottomText\&.pad"

.PP
Definition at line 145 of file curseshelpers\&.py\&.
.SS "curseshelpers\&.BottomText\&.parent"

.PP
Definition at line 141 of file curseshelpers\&.py\&.
.SS "curseshelpers\&.BottomText\&.text"

.PP
Definition at line 146 of file curseshelpers\&.py\&.
.PP
Referenced by curseshelpers\&.BottomText\&._redraw(), curseshelpers\&.MultiText\&._redraw(), curseshelpers\&.BottomText\&.addText(), curseshelpers\&.BottomText\&.clear(), curseshelpers\&.MultiText\&.clear(), and curseshelpers\&.Text\&.setText()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
