.TH "lheanalyzer.LorentzVector" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lheanalyzer.LorentzVector \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBadd\fP"
.br
.ti -1c
.RI "def \fBinvariantMass\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpx\fP"
.br
.ti -1c
.RI "\fBpy\fP"
.br
.ti -1c
.RI "\fBpz\fP"
.br
.ti -1c
.RI "\fBenergy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 119 of file lheanalyzer\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lheanalyzer\&.LorentzVector\&.__init__ (self, momentum)"

.PP
Definition at line 120 of file lheanalyzer\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lheanalyzer\&.LorentzVector\&.add (self, p)"

.PP
Definition at line 125 of file lheanalyzer\&.py\&.
.PP
References lheanalyzer\&.Particle\&.energy, lheanalyzer\&.LorentzVector\&.energy, lheanalyzer\&.Particle\&.px, lheanalyzer\&.LorentzVector\&.px, lheanalyzer\&.Particle\&.py, lheanalyzer\&.LorentzVector\&.py, lheanalyzer\&.Particle\&.pz, and lheanalyzer\&.LorentzVector\&.pz\&.
.PP
Referenced by rootplotlib\&.Legend\&.AddEntry()\&.
.SS "def lheanalyzer\&.LorentzVector\&.invariantMass (self)"

.PP
Definition at line 130 of file lheanalyzer\&.py\&.
.PP
References lheanalyzer\&.Particle\&.energy, lheanalyzer\&.LorentzVector\&.energy, lheanalyzer\&.Particle\&.px, lheanalyzer\&.LorentzVector\&.px, lheanalyzer\&.Particle\&.py, lheanalyzer\&.LorentzVector\&.py, lheanalyzer\&.Particle\&.pz, and lheanalyzer\&.LorentzVector\&.pz\&.
.SH "Member Data Documentation"
.PP 
.SS "lheanalyzer\&.LorentzVector\&.energy"

.PP
Definition at line 124 of file lheanalyzer\&.py\&.
.PP
Referenced by lheanalyzer\&.LorentzVector\&.add(), and lheanalyzer\&.LorentzVector\&.invariantMass()\&.
.SS "lheanalyzer\&.LorentzVector\&.px"

.PP
Definition at line 121 of file lheanalyzer\&.py\&.
.PP
Referenced by lheanalyzer\&.LorentzVector\&.add(), and lheanalyzer\&.LorentzVector\&.invariantMass()\&.
.SS "lheanalyzer\&.LorentzVector\&.py"

.PP
Definition at line 122 of file lheanalyzer\&.py\&.
.PP
Referenced by lheanalyzer\&.LorentzVector\&.add(), and lheanalyzer\&.LorentzVector\&.invariantMass()\&.
.SS "lheanalyzer\&.LorentzVector\&.pz"

.PP
Definition at line 123 of file lheanalyzer\&.py\&.
.PP
Referenced by lheanalyzer\&.LorentzVector\&.add(), and lheanalyzer\&.LorentzVector\&.invariantMass()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
