.TH "lheanalyzer.Event" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lheanalyzer.Event \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBaddParticle\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQCDCoupling\fP"
.br
.ti -1c
.RI "\fBparticles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file lheanalyzer\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lheanalyzer\&.Event\&.__init__ (self, initstr)"

.PP
.nf
Constuctor call with line from lhe file
.fi
.PP
 
.PP
Definition at line 37 of file lheanalyzer\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lheanalyzer\&.Event\&.addParticle (self, particle)"

.PP
.nf
adds a particle to the event
.fi
.PP
 
.PP
Definition at line 42 of file lheanalyzer\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lheanalyzer\&.Event\&.particles"

.PP
Definition at line 41 of file lheanalyzer\&.py\&.
.SS "lheanalyzer\&.Event\&.QCDCoupling"

.PP
Definition at line 40 of file lheanalyzer\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
