.TH "md_README" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- libs3a 
This repository contains libraries for the TAPAS framework\&.
.PP
Some rules for people who like to contribute:
.IP "\(bu" 2
Please make sure to push only sufficiently documented code to this repo ! This means at least meaningful dicstring and full doxygen markup as best practice\&.
.IP "\(bu" 2
The repo should contain only libraries, this means functions to be used in other standalone applications\&.
.PP
.PP
Additional information can be found in the doxygen documentation: http://aachen-3a.github.io/libs3a 
