.TH "python/rounding.py" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/rounding.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrounding\&.rounding\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBrounding\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
