.TH "aix3adb.aix3adb" 3 "Fri Jan 30 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aix3adb.aix3adb \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBaix3adb\&.aix3adbAuth\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBauthorize\fP"
.br
.ti -1c
.RI "def \fBobtainSSOCookies\fP"
.br
.ti -1c
.RI "def \fBdestroyauth\fP"
.br
.ti -1c
.RI "def \fBgetAuthServerProxy\fP"
.br
.ti -1c
.RI "def \fBinsertMCSample\fP"
.br
.ti -1c
.RI "def \fBinsertDataSample\fP"
.br
.ti -1c
.RI "def \fBinsertMCSkim\fP"
.br
.ti -1c
.RI "def \fBinsertDataSkim\fP"
.br
.ti -1c
.RI "def \fBeditMCSample\fP"
.br
.ti -1c
.RI "def \fBeditDataSample\fP"
.br
.ti -1c
.RI "def \fBeditMCSkim\fP"
.br
.ti -1c
.RI "def \fBeditDataSkim\fP"
.br
.ti -1c
.RI "def \fBgetMCSample\fP"
.br
.ti -1c
.RI "def \fBgetDataSample\fP"
.br
.ti -1c
.RI "def \fBgetMCSkim\fP"
.br
.ti -1c
.RI "def \fBgetDataSkim\fP"
.br
.ti -1c
.RI "def \fBgetMCLatestSkimAndSampleBySample\fP"
.br
.ti -1c
.RI "def \fBgetDataLatestSkimAndSampleBySample\fP"
.br
.ti -1c
.RI "def \fBgetMCSkimAndSampleBySkim\fP"
.br
.ti -1c
.RI "def \fBgetDataSkimAndSampleBySkim\fP"
.br
.ti -1c
.RI "def \fBgetMCSkimAndSample\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcookiefile\fP"
.br
.ti -1c
.RI "\fBauthurl\fP"
.br
.ti -1c
.RI "\fBreadurl\fP"
.br
.ti -1c
.RI "\fBdomain\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file aix3adb\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def aix3adb\&.aix3adb\&.__init__ (self, cookiefilepath = \fC'\fBaix3adb\fP-ssocookie\&.txt'\fP)"

.PP
Definition at line 43 of file aix3adb\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def aix3adb\&.aix3adb\&.authorize (self, username = \fCNone\fP, trykerberos = \fC3\fP)"

.PP
Definition at line 51 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.obtainSSOCookies()\&.
.PP
Referenced by aix3adb_deprecated\&.aix3adbAuth\&.__init__(), aix3adb\&.aix3adbAuth\&.__init__(), and aix3adb_deprecated\&.aix3adb\&.tryServerAuthFunction()\&.
.SS "def aix3adb\&.aix3adb\&.destroyauth (self)"

.PP
Definition at line 67 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.cookiefile\&.
.PP
Referenced by aix3adb_deprecated\&.aix3adbAuth\&.__del__(), aix3adb\&.aix3adbAuth\&.__del__(), and aix3adb_deprecated\&.aix3adb\&.tryServerAuthFunction()\&.
.SS "def aix3adb\&.aix3adb\&.editDataSample (self, name, sample)"

.PP
Definition at line 102 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.getAuthServerProxy()\&.
.SS "def aix3adb\&.aix3adb\&.editDataSkim (self, skimid, skim)"

.PP
Definition at line 110 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.getAuthServerProxy()\&.
.SS "def aix3adb\&.aix3adb\&.editMCSample (self, name, sample)"

.PP
Definition at line 98 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.getAuthServerProxy()\&.
.SS "def aix3adb\&.aix3adb\&.editMCSkim (self, skimid, skim)"

.PP
Definition at line 106 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.getAuthServerProxy()\&.
.SS "def aix3adb\&.aix3adb\&.getAuthServerProxy (self)"

.PP
Definition at line 72 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.authurl, aix3adb\&.aix3adb\&.cookiefile, aix3adb\&.aix3adb\&.domain, and aix3adb\&.transport()\&.
.PP
Referenced by aix3adb_deprecated\&.aix3adb\&.doEditDataSample(), aix3adb_deprecated\&.aix3adb\&.doEditMCSample(), aix3adb_deprecated\&.aix3adb\&.doRegisterDataSample(), aix3adb_deprecated\&.aix3adb\&.doRegisterMCSample(), aix3adb\&.aix3adb\&.editDataSample(), aix3adb\&.aix3adb\&.editDataSkim(), aix3adb\&.aix3adb\&.editMCSample(), aix3adb\&.aix3adb\&.editMCSkim(), aix3adb\&.aix3adb\&.insertDataSample(), aix3adb\&.aix3adb\&.insertDataSkim(), aix3adb\&.aix3adb\&.insertMCSample(), aix3adb\&.aix3adb\&.insertMCSkim(), aix3adb_deprecated\&.aix3adb\&.insertOrReplaceMCTags(), and aix3adb_deprecated\&.aix3adb\&.test()\&.
.SS "def aix3adb\&.aix3adb\&.getDataLatestSkimAndSampleBySample (self, name)"

.PP
Definition at line 130 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.readurl\&.
.SS "def aix3adb\&.aix3adb\&.getDataSample (self, name)"

.PP
Definition at line 117 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.readurl\&.
.SS "def aix3adb\&.aix3adb\&.getDataSkim (self, skimid)"

.PP
Definition at line 123 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.readurl\&.
.SS "def aix3adb\&.aix3adb\&.getDataSkimAndSampleBySkim (self, skimid)"

.PP
Definition at line 138 of file aix3adb\&.py\&.
.SS "def aix3adb\&.aix3adb\&.getMCLatestSkimAndSampleBySample (self, name)"

.PP
Definition at line 126 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.readurl\&.
.PP
Referenced by aix3adb\&.aix3adb\&.getMCSkimAndSample()\&.
.SS "def aix3adb\&.aix3adb\&.getMCSample (self, name)"

.PP
Definition at line 114 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.readurl\&.
.SS "def aix3adb\&.aix3adb\&.getMCSkim (self, skimid)"

.PP
Definition at line 120 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.readurl\&.
.SS "def aix3adb\&.aix3adb\&.getMCSkimAndSample (self, name = \fCNone\fP, skimid = \fCNone\fP)"

.PP
Definition at line 142 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.getMCLatestSkimAndSampleBySample(), and aix3adb\&.aix3adb\&.getMCSkimAndSampleBySkim()\&.
.SS "def aix3adb\&.aix3adb\&.getMCSkimAndSampleBySkim (self, skimid)"

.PP
Definition at line 134 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.readurl\&.
.PP
Referenced by aix3adb\&.aix3adb\&.getMCSkimAndSample()\&.
.SS "def aix3adb\&.aix3adb\&.insertDataSample (self, sample)"

.PP
Definition at line 85 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.getAuthServerProxy()\&.
.SS "def aix3adb\&.aix3adb\&.insertDataSkim (self, skim)"

.PP
Definition at line 93 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.getAuthServerProxy()\&.
.SS "def aix3adb\&.aix3adb\&.insertMCSample (self, sample)"

.PP
Definition at line 79 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.getAuthServerProxy()\&.
.SS "def aix3adb\&.aix3adb\&.insertMCSkim (self, skim)"

.PP
Definition at line 89 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.getAuthServerProxy()\&.
.SS "def aix3adb\&.aix3adb\&.obtainSSOCookies (self)"

.PP
Definition at line 62 of file aix3adb\&.py\&.
.PP
References aix3adb\&.aix3adb\&.authurl, and aix3adb\&.aix3adb\&.cookiefile\&.
.PP
Referenced by aix3adb_deprecated\&.aix3adb\&.authorize(), and aix3adb\&.aix3adb\&.authorize()\&.
.SH "Member Data Documentation"
.PP 
.SS "aix3adb\&.aix3adb\&.authurl"

.PP
Definition at line 45 of file aix3adb\&.py\&.
.PP
Referenced by aix3adb_deprecated\&.aix3adb\&.getAuthServerProxy(), aix3adb\&.aix3adb\&.getAuthServerProxy(), aix3adb_deprecated\&.aix3adb\&.obtainSSOCookies(), and aix3adb\&.aix3adb\&.obtainSSOCookies()\&.
.SS "aix3adb\&.aix3adb\&.cookiefile"

.PP
Definition at line 44 of file aix3adb\&.py\&.
.PP
Referenced by aix3adb_deprecated\&.aix3adb\&.destroyauth(), aix3adb\&.aix3adb\&.destroyauth(), aix3adb_deprecated\&.aix3adb\&.getAuthServerProxy(), aix3adb\&.aix3adb\&.getAuthServerProxy(), aix3adb_deprecated\&.aix3adb\&.obtainSSOCookies(), and aix3adb\&.aix3adb\&.obtainSSOCookies()\&.
.SS "aix3adb\&.aix3adb\&.domain"

.PP
Definition at line 47 of file aix3adb\&.py\&.
.PP
Referenced by aix3adb_deprecated\&.aix3adb\&.getAuthServerProxy(), and aix3adb\&.aix3adb\&.getAuthServerProxy()\&.
.SS "aix3adb\&.aix3adb\&.readurl"

.PP
Definition at line 46 of file aix3adb\&.py\&.
.PP
Referenced by aix3adb\&.aix3adb\&.getDataLatestSkimAndSampleBySample(), aix3adb_deprecated\&.aix3adb\&.getDataSample(), aix3adb\&.aix3adb\&.getDataSample(), aix3adb\&.aix3adb\&.getDataSkim(), aix3adb\&.aix3adb\&.getMCLatestSkimAndSampleBySample(), aix3adb_deprecated\&.aix3adb\&.getMCSample(), aix3adb\&.aix3adb\&.getMCSample(), aix3adb\&.aix3adb\&.getMCSkim(), aix3adb\&.aix3adb\&.getMCSkimAndSampleBySkim(), aix3adb_deprecated\&.aix3adb\&.searchDataSamples(), and aix3adb_deprecated\&.aix3adb\&.searchMCSamples()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
