.TH "aix3adb.cookietransport" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aix3adb.cookietransport \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaix3adb\&.cookietransportrequest\fP, and Transport\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetcookies\fP"
.br
.ti -1c
.RI "def \fBsend_cookies\fP"
.br
.ti -1c
.RI "def \fBrequest\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcookies\fP"
.br
.ti -1c
.RI "\fBverbose\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBcookies\fP = []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 236 of file aix3adb\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def aix3adb\&.cookietransportrequest\&.request (self, host, handler, request_body, verbose = \fC0\fP)\fC [inherited]\fP"

.PP
Definition at line 195 of file aix3adb\&.py\&.
.SS "def aix3adb\&.cookietransportrequest\&.send_cookies (self, connection)\fC [inherited]\fP"

.PP
Definition at line 190 of file aix3adb\&.py\&.
.PP
References aix3adb\&.cookietransportrequest\&.cookies\&.
.SS "def aix3adb\&.cookietransportrequest\&.setcookies (self, cookiefile, domain)\fC [inherited]\fP"

.PP
Definition at line 183 of file aix3adb\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "list aix3adb\&.cookietransportrequest\&.cookies = []\fC [static]\fP, \fC [inherited]\fP"

.PP
Definition at line 182 of file aix3adb\&.py\&.
.PP
Referenced by aix3adb_deprecated\&.cookietransportrequest\&.send_cookies(), and aix3adb\&.cookietransportrequest\&.send_cookies()\&.
.SS "aix3adb\&.cookietransportrequest\&.cookies\fC [inherited]\fP"

.PP
Definition at line 184 of file aix3adb\&.py\&.
.PP
Referenced by aix3adb_deprecated\&.cookietransportrequest\&.send_cookies()\&.
.SS "aix3adb\&.cookietransportrequest\&.verbose\fC [inherited]\fP"

.PP
Definition at line 196 of file aix3adb\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
