.TH "aix3adb.Aix3adbException" 3 "Fri Jan 30 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aix3adb.Aix3adbException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 
Definition at line 20 of file aix3adb\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
