.TH "binConfig_example" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binConfig_example \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBcpFiles\fP = ['bin','ConfigFiles','lib']"
.br
.ti -1c
.RI "tuple \fBPathtoExecutable\fP = os\&.getenv( 'MUSIC_BASE' )"
.br
.ti -1c
.RI "string \fBoutDir\fP = '/user/USER/out'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list binConfig_example\&.cpFiles = ['bin','ConfigFiles','lib']"

.PP
Definition at line 2 of file binConfig_example\&.py\&.
.SS "string binConfig_example\&.outDir = '/user/USER/out'"

.PP
Definition at line 4 of file binConfig_example\&.py\&.
.SS "tuple binConfig_example\&.PathtoExecutable = os\&.getenv( 'MUSIC_BASE' )"

.PP
Definition at line 3 of file binConfig_example\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
