.TH "binConfig_example" 3 "30 Jan 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binConfig_example \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBcpFiles\fP = ['bin','ConfigFiles','lib']"
.br
.ti -1c
.RI "tuple \fBPathtoExecutable\fP = os.getenv( 'MUSIC_BASE' )"
.br
.ti -1c
.RI "string \fBoutDir\fP = '/user/USER/out'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list \fBbinConfig_example::cpFiles\fP = ['bin','ConfigFiles','lib']"
.PP
Definition at line 2 of file binConfig_example.py.
.SS "string \fBbinConfig_example::outDir\fP = '/user/USER/out'"
.PP
Definition at line 4 of file binConfig_example.py.
.SS "tuple \fBbinConfig_example::PathtoExecutable\fP = os.getenv( 'MUSIC_BASE' )"
.PP
Definition at line 3 of file binConfig_example.py.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code.
