.TH "python/cesubmit.py" 3 "Fri Jan 30 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/cesubmit.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcesubmit\&.Job\fP"
.br
.ti -1c
.RI "class \fBcesubmit\&.Task\fP"
.br
.ti -1c
.RI "class \fBcesubmit\&.ProxyError\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBcesubmit\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcesubmit\&.submitWorker\fP"
.br
.ti -1c
.RI "def \fBcesubmit\&.resubmitWorker\fP"
.br
.ti -1c
.RI "def \fBcesubmit\&.killWorker\fP"
.br
.ti -1c
.RI "def \fBcesubmit\&.parseGetOutput\fP"
.br
.ti -1c
.RI "def \fBcesubmit\&.parseStatus\fP"
.br
.ti -1c
.RI "def \fBcesubmit\&.parseStatusMultiple\fP"
.br
.ti -1c
.RI "def \fBcesubmit\&.parseStatusMultipleL1\fP"
.br
.ti -1c
.RI "def \fBcesubmit\&.chunks\fP"
.br
.ti -1c
.RI "def \fBcesubmit\&.timeLeftVomsProxy\fP"
.br
.ti -1c
.RI "def \fBcesubmit\&.checkVomsProxy\fP"
.br
.ti -1c
.RI "def \fBcesubmit\&.renewVomsProxy\fP"
.br
.ti -1c
.RI "def \fBcesubmit\&.checkAndRenewVomsProxy\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBcesubmit\&.log\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
