.TH "crabFunctions.CrabController" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crabFunctions.CrabController \- 
.PP
The \fBCrabController\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIThe constructor\&. \fP"
.ti -1c
.RI "def \fBcheckwrite\fP"
.br
.RI "\fICheck if crab can write to specified site\&. \fP"
.ti -1c
.RI "def \fBsubmit\fP"
.br
.RI "\fICheck if crab can write to specified site\&. \fP"
.ti -1c
.RI "def \fBresubmit\fP"
.br
.RI "\fIResubmit all failed tasks in job or specified list of jobs in task\&. \fP"
.ti -1c
.RI "def \fBcheckusername\fP"
.br
.RI "\fIReturns the hn name for a user with valid proxy\&. \fP"
.ti -1c
.RI "def \fBstatus\fP"
.br
.RI "\fICheck crab status\&. \fP"
.ti -1c
.RI "def \fBcommandlineOptions\fP"
.br
.RI "\fIPopulates an existing optparse parser or returns a new one with options for crab functions\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBworkingArea\fP"
.br
.ti -1c
.RI "\fBdry_run\fP"
.br
.ti -1c
.RI "\fBvoGroup\fP"
.br
.ti -1c
.RI "\fBusername\fP"
.br
.ti -1c
.RI "\fBlogger\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBCrabController\fP class\&. 

This class can be used to manage Analyses using crab3 
.PP
Definition at line 20 of file crabFunctions\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def crabFunctions\&.CrabController\&.__init__ (self, logger = \fCNone\fP, workingArea = \fCNone\fP, voGroup = \fCNone\fP, username = \fCNone\fP)"

.PP
The constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&. 
.br
\fIlogger,:\fP A previously defined logger instance\&. Crab log messages will use this logger as their parent logger\&. 
.br
\fIworkingArea\fP path to a workingArea where subprocesses should be run (e\&.g\&. crab commands) 
.br
\fIvoGroup\fP The virtual organisation you belong to 
.br
\fIusername\fP Useres Hypernews username 
.RE
.PP

.PP
Definition at line 28 of file crabFunctions\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def crabFunctions\&.CrabController\&.checkusername (self)"

.PP
Returns the hn name for a user with valid proxy\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
users hypernews name 
.RE
.PP

.PP
Definition at line 130 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabController\&.username, and crabFunctions\&.CrabController\&.workingArea\&.
.PP
Referenced by crabFunctions\&.CrabController\&.checkwrite()\&.
.SS "def crabFunctions\&.CrabController\&.checkwrite (self, site = \fC'T2_DE_RWTH'\fP, path = \fC'noPath'\fP)"

.PP
Check if crab can write to specified site\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&. 
.br
\fIsite\fP The Site symbol [default:T2_DE_RWTH] 
.br
\fIpath\fP lfn path to check write permission in\&. see twiki WorkBookCRAB3Tutorial 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean which is True if user can write to site and False otherwise 
.RE
.PP

.PP
Definition at line 73 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabController\&.checkusername(), crabFunctions\&.CrabController\&.username, crabFunctions\&.CrabController\&.voGroup, and crabFunctions\&.CrabController\&.workingArea\&.
.SS "def crabFunctions\&.CrabController\&.commandlineOptions (self, parser = \fCoptparse\&.OptionParser( 'usage: %prog' )\fP)"

.PP
Populates an existing optparse parser or returns a new one with options for crab functions\&. This functions populates a previously created (or new) instance of a optparse parser object with options needed by crab functions\&. It is possible to add three kinds of options:
.IP "\(bu" 2
options where a error should be raised if the option was previously defined
.IP "\(bu" 2
options where previous definitions should be kept
.IP "\(bu" 2
options where previous definitions should be overriden
.PP
.PP
\fBParameters:\fP
.RS 4
\fIparser\fP A previously created parser oject which should be extenden [default: new instance] 
.RE
.PP
\fBReturns:\fP
.RS 4
A new or extenden optparse parser instance 
.RE
.PP

.PP
Definition at line 203 of file crabFunctions\&.py\&.
.SS "def crabFunctions\&.CrabController\&.resubmit (self, name, joblist = \fCNone\fP)"

.PP
Resubmit all failed tasks in job or specified list of jobs in task\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&. 
.br
\fIname\fP The crab3 request name, a\&.k\&.a the sample name 
.br
\fIjoblist\fP The crab3 request name, a\&.k\&.a the sample name 
.RE
.PP

.PP
Definition at line 112 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabController\&.dry_run, and crabFunctions\&.CrabController\&.workingArea\&.
.SS "def crabFunctions\&.CrabController\&.status (self, name)"

.PP
Check crab status\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&. 
.br
\fIname\fP The crab3 request name, a\&.k\&.a the sample name (string) 
.RE
.PP

.PP
Definition at line 148 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabController\&.dry_run, and crabFunctions\&.CrabController\&.workingArea\&.
.SS "def crabFunctions\&.CrabController\&.submit (self, name)"

.PP
Check if crab can write to specified site\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&. 
.br
\fIname\fP The crab3 request name, a\&.k\&.a the sample name 
.RE
.PP

.PP
Definition at line 96 of file crabFunctions\&.py\&.
.PP
References crabFunctions\&.CrabController\&.dry_run, crabFunctions\&.CrabController\&.voGroup, and crabFunctions\&.CrabController\&.workingArea\&.
.SH "Member Data Documentation"
.PP 
.SS "crabFunctions\&.CrabController\&.dry_run"

.PP
Definition at line 33 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabController\&.resubmit(), crabFunctions\&.CrabController\&.status(), and crabFunctions\&.CrabController\&.submit()\&.
.SS "crabFunctions\&.CrabController\&.logger"

.PP
Definition at line 44 of file crabFunctions\&.py\&.
.SS "crabFunctions\&.CrabController\&.username"

.PP
Definition at line 39 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabController\&.checkusername(), and crabFunctions\&.CrabController\&.checkwrite()\&.
.SS "crabFunctions\&.CrabController\&.voGroup"

.PP
Definition at line 35 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabController\&.checkwrite(), and crabFunctions\&.CrabController\&.submit()\&.
.SS "crabFunctions\&.CrabController\&.workingArea"

.PP
Definition at line 30 of file crabFunctions\&.py\&.
.PP
Referenced by crabFunctions\&.CrabController\&.checkusername(), crabFunctions\&.CrabController\&.checkwrite(), crabFunctions\&.CrabController\&.resubmit(), crabFunctions\&.CrabController\&.status(), and crabFunctions\&.CrabController\&.submit()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
