crabFunctions.TaskStats
NAME
crabFunctions.TaskStats -
Class holds job statistics for several Crab tasks.
SYNOPSIS
Public Member Functions
def __init__
The object constructor.
def updateStats
This function updates the statistics for a given tasklist.
def clearStats
This function sets all counts to zero.
Public Attributes
nTasks
nUnsubmitted
nIdle
nRunning
nTransferring
nCooloff
nFailed
nFinished
nComplete
Detailed Description
Class holds job statistics for several Crab tasks.
This class saves and updates statistics from a given list of CrabTask objects.
Definition at line 341 of file crabFunctions.py.
Constructor & Destructor Documentation
def crabFunctions.TaskStats.__init__ (self, tasklist = None)
The object constructor.
Parameters:
self,: The object pointer.
tasklist,: (Optional) List of CrabTasks for which statistics should be calculated
Definition at line 347 of file crabFunctions.py.
References crabFunctions.TaskStats.clearStats(), and crabFunctions.TaskStats.updateStats().
Member Function Documentation
def crabFunctions.TaskStats.clearStats (self)
This function sets all counts to zero.
Parameters:
self,: The object pointer.
Definition at line 374 of file crabFunctions.py.
References crabFunctions.TaskStats.nTasks.
Referenced by crabFunctions.TaskStats.__init__(), and crabFunctions.TaskStats.updateStats().
def crabFunctions.TaskStats.updateStats (self, tasklist)
This function updates the statistics for a given tasklist.
Parameters:
self,: The object pointer.
tasklist,: List of CrabTasks for which statistics should be calculated
Definition at line 357 of file crabFunctions.py.
References crabFunctions.TaskStats.clearStats().
Referenced by crabFunctions.TaskStats.__init__().
Member Data Documentation
crabFunctions.TaskStats.nComplete
Definition at line 383 of file crabFunctions.py.
crabFunctions.TaskStats.nCooloff
Definition at line 380 of file crabFunctions.py.
crabFunctions.TaskStats.nFailed
Definition at line 381 of file crabFunctions.py.
crabFunctions.TaskStats.nFinished
Definition at line 382 of file crabFunctions.py.
crabFunctions.TaskStats.nIdle
Definition at line 377 of file crabFunctions.py.
crabFunctions.TaskStats.nRunning
Definition at line 378 of file crabFunctions.py.
crabFunctions.TaskStats.nTasks
Definition at line 359 of file crabFunctions.py.
Referenced by crabFunctions.TaskStats.clearStats().
crabFunctions.TaskStats.nTransferring
Definition at line 379 of file crabFunctions.py.
crabFunctions.TaskStats.nUnsubmitted
Definition at line 376 of file crabFunctions.py.
Author
Generated automatically by Doxygen for Aachen-3A from the source code.