curseshelpers.CursesMultiHandler
NAME
curseshelpers.CursesMultiHandler -
SYNOPSIS
Inherits Handler.
Public Member Functions
def __init__
def setFormatter
def receive
def send
def emit
def close
Public Attributes
queue
Private Member Functions
def _format_record
Private Attributes
_handler
Detailed Description
Definition at line 442 of file curseshelpers.py.
Constructor & Destructor Documentation
def curseshelpers.CursesMultiHandler.__init__ (self, stdscr, bottomText, log_q, level = logging.DEBUG)
Definition at line 443 of file curseshelpers.py.
Member Function Documentation
def curseshelpers.CursesMultiHandler._format_record (self, record) [private]
Definition at line 475 of file curseshelpers.py.
Referenced by curseshelpers.CursesMultiHandler.emit().
def curseshelpers.CursesMultiHandler.close (self)
Definition at line 498 of file curseshelpers.py.
def curseshelpers.CursesMultiHandler.emit (self, record)
Definition at line 489 of file curseshelpers.py.
References curseshelpers.CursesMultiHandler._format_record(), and curseshelpers.CursesMultiHandler.send().
def curseshelpers.CursesMultiHandler.receive (self)
Definition at line 458 of file curseshelpers.py.
def curseshelpers.CursesMultiHandler.send (self, s)
Definition at line 472 of file curseshelpers.py.
Referenced by curseshelpers.CursesMultiHandler.emit().
def curseshelpers.CursesMultiHandler.setFormatter (self, fmt)
Definition at line 454 of file curseshelpers.py.
Member Data Documentation
curseshelpers.CursesMultiHandler._handler [private]
Definition at line 446 of file curseshelpers.py.
curseshelpers.CursesMultiHandler.queue
Definition at line 448 of file curseshelpers.py.
Author
Generated automatically by Doxygen for libs3a from the source code.