.TH "curseshelpers.BaseElement" 3 "Fri Jan 30 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curseshelpers.BaseElement \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcurseshelpers\&.BottomText\fP, \fBcurseshelpers\&.MultiText\fP, \fBcurseshelpers\&.SelectTable\fP, \fBcurseshelpers\&.TabbedText\fP, and \fBcurseshelpers\&.Text\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBrefresh\fP"
.br
.ti -1c
.RI "def \fBgoLeft\fP"
.br
.ti -1c
.RI "def \fBgoRight\fP"
.br
.ti -1c
.RI "def \fBgoUp\fP"
.br
.ti -1c
.RI "def \fBgoDown\fP"
.br
.ti -1c
.RI "def \fBpageUp\fP"
.br
.ti -1c
.RI "def \fBpageDown\fP"
.br
.ti -1c
.RI "def \fBhome\fP"
.br
.ti -1c
.RI "def \fBend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file curseshelpers\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def curseshelpers\&.BaseElement\&.end (self)"

.PP
Definition at line 43 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.goDown (self)"

.PP
Definition at line 35 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.goLeft (self)"

.PP
Definition at line 29 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.goRight (self)"

.PP
Definition at line 31 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.goUp (self)"

.PP
Definition at line 33 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.home (self)"

.PP
Definition at line 41 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.pageDown (self)"

.PP
Definition at line 39 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.pageUp (self)"

.PP
Definition at line 37 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.BaseElement\&.refresh (self)"

.PP
Definition at line 27 of file curseshelpers\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
