.TH "curseshelpers" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curseshelpers \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseElement\fP"
.br
.ti -1c
.RI "class \fBTabbedText\fP"
.br
.ti -1c
.RI "class \fBBottomText\fP"
.br
.ti -1c
.RI "class \fBMultiText\fP"
.br
.ti -1c
.RI "class \fBText\fP"
.br
.ti -1c
.RI "class \fBSelectTable\fP"
.br
.ti -1c
.RI "class \fBStdOutWrapper\fP"
.br
.ti -1c
.RI "class \fBCursesHandler\fP"
.br
.ti -1c
.RI "class \fBCursesMultiHandler\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBtest\fP"
.br
.ti -1c
.RI "def \fBdefault\fP"
.br
.ti -1c
.RI "def \fBchunks\fP"
.br
.ti -1c
.RI "def \fBcolWidthsReducerMaximum\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBlogger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def curseshelpers\&.chunks (l, n)"

.PP
.nf
Yield successive n-sized chunks from l.

.fi
.PP
 
.PP
Definition at line 20 of file curseshelpers\&.py\&.
.PP
Referenced by curseshelpers\&.TabbedText\&._redraw(), curseshelpers\&.BottomText\&._redraw(), curseshelpers\&.MultiText\&._redraw(), and curseshelpers\&.Text\&._redraw()\&.
.SS "def curseshelpers\&.colWidthsReducerMaximum (colWidths, totalWidth)"

.PP
Definition at line 284 of file curseshelpers\&.py\&.
.SS "def curseshelpers\&.default (x, y)"

.PP
Definition at line 17 of file curseshelpers\&.py\&.
.PP
Referenced by curseshelpers\&.SelectTable\&.addRow()\&.
.SS "def curseshelpers\&.test ()"

.PP
Definition at line 15 of file curseshelpers\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "tuple curseshelpers\&.logger = logging\&.getLogger(__name__)"

.PP
Definition at line 13 of file curseshelpers\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
