curseshelpers
NAME
curseshelpers -
SYNOPSIS
Classes
class BaseElement
class TabbedText
class BottomText
class MultiText
class Text
class SelectTable
class StdOutWrapper
class CursesHandler
class CursesMultiHandler
Functions
def test
def default
def chunks
def colWidthsReducerMaximum
Variables
tuple logger = logging.getLogger(__name__)
Function Documentation
def curseshelpers.chunks (l, n)
Yield successive n-sized chunks from l.
Definition at line 20 of file curseshelpers.py.
Referenced by curseshelpers.TabbedText._redraw(), curseshelpers.BottomText._redraw(), curseshelpers.MultiText._redraw(), and curseshelpers.Text._redraw().
def curseshelpers.colWidthsReducerMaximum (colWidths, totalWidth)
Definition at line 284 of file curseshelpers.py.
def curseshelpers.default (x, y)
Definition at line 17 of file curseshelpers.py.
Referenced by curseshelpers.SelectTable.addRow().
def curseshelpers.test ()
Definition at line 15 of file curseshelpers.py.
Variable Documentation
tuple curseshelpers.logger = logging.getLogger(__name__)
Definition at line 13 of file curseshelpers.py.
Author
Generated automatically by Doxygen for Aachen-3A from the source code.