.TH "python/dbconfigmanager.py" 3 "30 Jan 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/dbconfigmanager.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdbconfigmanager::DBConfigManager\fP"
.br
.RI "\fIDatabase config manager class. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdbconfigmanager\fP"
.br
.PP

.RI "\fITool to manage config files of samples stored in a database. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBdbconfigmanager::main\fP"
.br
.RI "\fI\fBmain()\fP method for testing purposes \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBdbconfigmanager::log\fP = logging.getLogger('dbconfigmanager')"
.br
.RI "\fILogger object. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code.
