.TH "dbutilscms.McMUtilities" 3 "Fri Jan 30 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbutilscms.McMUtilities \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBreadJSON\fP"
.br
.ti -1c
.RI "def \fBreadURL\fP"
.br
.ti -1c
.RI "def \fBgetGenInfo\fP"
.br
.ti -1c
.RI "def \fBgetCrossSection\fP"
.br
.ti -1c
.RI "def \fBgetFilterEfficiency\fP"
.br
.ti -1c
.RI "def \fBgetInfo\fP"
.br
.ti -1c
.RI "def \fBgetEvents\fP"
.br
.ti -1c
.RI "def \fBgetGenerators\fP"
.br
.ti -1c
.RI "def \fBgetEnergy\fP"
.br
.ti -1c
.RI "def \fBgetCMSSW\fP"
.br
.ti -1c
.RI "def \fBgetWorkingGroup\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmcm_prefix\fP"
.br
.ti -1c
.RI "\fBmcm_json\fP"
.br
.ti -1c
.RI "\fBgen_json\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file dbutilscms\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def dbutilscms\&.McMUtilities\&.__init__ (self)"

.PP
Definition at line 18 of file dbutilscms\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def dbutilscms\&.McMUtilities\&.getCMSSW (self)"

.PP
Definition at line 105 of file dbutilscms\&.py\&.
.PP
References dbutilscms\&.McMUtilities\&.getInfo()\&.
.SS "def dbutilscms\&.McMUtilities\&.getCrossSection (self)"

.PP
Definition at line 77 of file dbutilscms\&.py\&.
.PP
References dbutilscms\&.McMUtilities\&.getGenInfo()\&.
.SS "def dbutilscms\&.McMUtilities\&.getEnergy (self)"

.PP
Definition at line 101 of file dbutilscms\&.py\&.
.PP
References dbutilscms\&.McMUtilities\&.getInfo()\&.
.SS "def dbutilscms\&.McMUtilities\&.getEvents (self)"

.PP
Definition at line 93 of file dbutilscms\&.py\&.
.PP
References dbutilscms\&.McMUtilities\&.getInfo()\&.
.SS "def dbutilscms\&.McMUtilities\&.getFilterEfficiency (self)"

.PP
Definition at line 81 of file dbutilscms\&.py\&.
.PP
References dbutilscms\&.McMUtilities\&.getGenInfo()\&.
.SS "def dbutilscms\&.McMUtilities\&.getGenerators (self)"

.PP
Definition at line 97 of file dbutilscms\&.py\&.
.PP
References dbutilscms\&.McMUtilities\&.getInfo()\&.
.SS "def dbutilscms\&.McMUtilities\&.getGenInfo (self, key)"

.PP
Definition at line 44 of file dbutilscms\&.py\&.
.PP
References dbutilscms\&.McMUtilities\&.gen_json, dbutilscms\&.McMUtilities\&.mcm_json, dbutilscms\&.McMUtilities\&.mcm_prefix, and dbutilscms\&.McMUtilities\&.readJSON()\&.
.PP
Referenced by dbutilscms\&.McMUtilities\&.getCrossSection(), and dbutilscms\&.McMUtilities\&.getFilterEfficiency()\&.
.SS "def dbutilscms\&.McMUtilities\&.getInfo (self, key)"

.PP
Definition at line 86 of file dbutilscms\&.py\&.
.PP
References dbutilscms\&.McMUtilities\&.mcm_json\&.
.PP
Referenced by dbutilscms\&.McMUtilities\&.getCMSSW(), dbutilscms\&.McMUtilities\&.getEnergy(), dbutilscms\&.McMUtilities\&.getEvents(), dbutilscms\&.McMUtilities\&.getGenerators(), and dbutilscms\&.McMUtilities\&.getWorkingGroup()\&.
.SS "def dbutilscms\&.McMUtilities\&.getWorkingGroup (self)"

.PP
Definition at line 109 of file dbutilscms\&.py\&.
.PP
References dbutilscms\&.McMUtilities\&.getInfo()\&.
.SS "def dbutilscms\&.McMUtilities\&.readJSON (self, json_string)"

.PP
Definition at line 24 of file dbutilscms\&.py\&.
.PP
Referenced by dbutilscms\&.McMUtilities\&.getGenInfo(), and dbutilscms\&.McMUtilities\&.readURL()\&.
.SS "def dbutilscms\&.McMUtilities\&.readURL (self, mcm_dataset)"

.PP
Definition at line 32 of file dbutilscms\&.py\&.
.PP
References dbutilscms\&.McMUtilities\&.gen_json, dbutilscms\&.McMUtilities\&.mcm_json, dbutilscms\&.McMUtilities\&.mcm_prefix, and dbutilscms\&.McMUtilities\&.readJSON()\&.
.SH "Member Data Documentation"
.PP 
.SS "dbutilscms\&.McMUtilities\&.gen_json"

.PP
Definition at line 21 of file dbutilscms\&.py\&.
.PP
Referenced by dbutilscms\&.McMUtilities\&.getGenInfo(), and dbutilscms\&.McMUtilities\&.readURL()\&.
.SS "dbutilscms\&.McMUtilities\&.mcm_json"

.PP
Definition at line 20 of file dbutilscms\&.py\&.
.PP
Referenced by dbutilscms\&.McMUtilities\&.getGenInfo(), dbutilscms\&.McMUtilities\&.getInfo(), and dbutilscms\&.McMUtilities\&.readURL()\&.
.SS "dbutilscms\&.McMUtilities\&.mcm_prefix"

.PP
Definition at line 19 of file dbutilscms\&.py\&.
.PP
Referenced by dbutilscms\&.McMUtilities\&.getGenInfo(), and dbutilscms\&.McMUtilities\&.readURL()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
