.TH "dbutilscms.DBSUtilities" 3 "Fri Jan 30 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbutilscms.DBSUtilities \- 
.PP
The \fBDBSUtilities\fP Class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIThe constructor\&. \fP"
.ti -1c
.RI "def \fBgetDatasetBlocks\fP"
.br
.RI "\fIFunction to get all detail blocks for a dataset\&. \fP"
.ti -1c
.RI "def \fBgetDatasetSummary\fP"
.br
.RI "\fIFunction to get a summary for a dataset\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdbsUrl\fP"
.br
.ti -1c
.RI "\fBdbsApi\fP"
.br
.ti -1c
.RI "\fBnumEvents\fP"
.br
.ti -1c
.RI "\fBnumFiles\fP"
.br
.ti -1c
.RI "\fBtotalFileSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBDBSUtilities\fP Class\&. 

This is a helper class for the dbs database 
.PP
Definition at line 116 of file dbutilscms\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def dbutilscms\&.DBSUtilities\&.__init__ (self)"

.PP
The constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&. 
.RE
.PP

.PP
Definition at line 120 of file dbutilscms\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def dbutilscms\&.DBSUtilities\&.getDatasetBlocks (self, dataset)"

.PP
Function to get all detail blocks for a dataset\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&. 
.br
\fIdataset\fP String - The dataset name 
.RE
.PP

.PP
Definition at line 130 of file dbutilscms\&.py\&.
.PP
Referenced by dbutilscms\&.DBSUtilities\&.getDatasetSummary()\&.
.SS "def dbutilscms\&.DBSUtilities\&.getDatasetSummary (self, dataset)"

.PP
Function to get a summary for a dataset\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself,:\fP The object pointer\&. 
.br
\fIdataset\fP String - The dataset name 
.RE
.PP

.PP
Definition at line 136 of file dbutilscms\&.py\&.
.PP
References dbutilscms\&.DBSUtilities\&.getDatasetBlocks()\&.
.SH "Member Data Documentation"
.PP 
.SS "dbutilscms\&.DBSUtilities\&.dbsApi"

.PP
Definition at line 122 of file dbutilscms\&.py\&.
.SS "dbutilscms\&.DBSUtilities\&.dbsUrl"

.PP
Definition at line 121 of file dbutilscms\&.py\&.
.SS "dbutilscms\&.DBSUtilities\&.numEvents"

.PP
Definition at line 123 of file dbutilscms\&.py\&.
.SS "dbutilscms\&.DBSUtilities\&.numFiles"

.PP
Definition at line 124 of file dbutilscms\&.py\&.
.SS "dbutilscms\&.DBSUtilities\&.totalFileSize"

.PP
Definition at line 125 of file dbutilscms\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
