.TH "githookcontroller" 3 "30 Jan 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
githookcontroller \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGitHookController\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBlog\fP = logging.getLogger( 'githookcontroller' )"
.br
.ti -1c
.RI "tuple \fBch\fP = logging.StreamHandler( sys.stdout )"
.br
.ti -1c
.RI "tuple \fBformatter\fP = logging.Formatter( '%(levelname)s (%(name)s): %(message)s' )"
.br
.ti -1c
.RI "tuple \fBPush\fP"
.br
.ti -1c
.RI "tuple \fBCommit\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def githookcontroller::main ()"
.PP
Definition at line 450 of file githookcontroller.py.
.SH "Variable Documentation"
.PP 
.SS "tuple \fBgithookcontroller::ch\fP = logging.StreamHandler( sys.stdout )"
.PP
Definition at line 37 of file githookcontroller.py.
.SS "tuple \fBgithookcontroller::Commit\fP"\fBInitial value:\fP
.PP
.nf
namedtuple('Commit', ['local_ref', 'local_sha1', 'remote_ref', 'remote_sha1',
                               'local_branch', 'remote_branch'])
.fi
.PP
Definition at line 45 of file githookcontroller.py.
.SS "tuple \fBgithookcontroller::formatter\fP = logging.Formatter( '%(levelname)s (%(name)s): %(message)s' )"
.PP
Definition at line 39 of file githookcontroller.py.
.SS "tuple \fBgithookcontroller::log\fP = logging.getLogger( 'githookcontroller' )"
.PP
Definition at line 35 of file githookcontroller.py.
.SS "tuple \fBgithookcontroller::Push\fP"\fBInitial value:\fP
.PP
.nf
namedtuple('Push', ['commits', 'remote_name', 'remote_url',
                           'current_branch', 'removing_remote', 'forcing'])
.fi
.PP
Definition at line 43 of file githookcontroller.py.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code.
