gridFunctions
NAME
gridFunctions -
This module provides common functions for interaction with the local Tier2.
SYNOPSIS
Functions
def getdcachelist
Get list of files with certain file extension in dCap folder recursively.
def timeLeftVomsProxy
Returns the life time left.
def checkVomsProxy
Checks if the proxy is valid longer than time.
def renewVomsProxy
Creates a new vom proxy.
def checkAndRenewVomsProxy
Checks if the proxy is valid longer than time and renew if needed.
Detailed Description
This module provides common functions for interaction with the local Tier2.
Function Documentation
def gridFunctions.checkAndRenewVomsProxy (time = 604800, voms = 'cms:/cms/dcms', passphrase = None)
Checks if the proxy is valid longer than time and renew if needed.
Parameters:
time,: reference time in seconds to check against
voms,: the voms group used to set up the server [default:cms:/cms/dcms]
passphrase,: Passphrase for GRID certificate [default:none]. The password request is send to the prompt if no passphrase given
Definition at line 95 of file gridFunctions.py.
References checkVomsProxy(), and renewVomsProxy().
def gridFunctions.checkVomsProxy (time = 86400)
Checks if the proxy is valid longer than time.
Parameters:
time,: integer reference time in seconds to check against
Returns:
boolean returns True if the proxy is valid longer than time, False otherwise.
Definition at line 68 of file gridFunctions.py.
References timeLeftVomsProxy().
Referenced by checkAndRenewVomsProxy().
def gridFunctions.getdcachelist (dir, Tag, mem_limit = 500000000, fileXtension = '.pxlio')
Get list of files with certain file extension in dCap folder recursively.
Parameters:
dir String containing the dCap folder without /pnfs/physik.rwth-aachen.de/cms/store/user/
Tag Tag parameter is depreceated and kept for compability with old versions of television
mem_limit Integer maximum summed filesize before files are splitted in sublists [default:500000000]
fileXtension file extension for which files should be listed
Definition at line 14 of file gridFunctions.py.
References HistClass.split().
Referenced by remote_example.getFilesfromFile().
def gridFunctions.renewVomsProxy (voms = 'cms:/cms/dcms', passphrase = None)
Creates a new vom proxy. This function creates a new
Parameters:
voms,: the voms group used to set up the server [default:cms:/cms/dcms]
passphrase,: Passphrase for GRID certificate [default:none]. The password request is send to the prompt if no passphrase given
Make a new proxy with a lifetime of one week.
Definition at line 77 of file gridFunctions.py.
Referenced by checkAndRenewVomsProxy().
def gridFunctions.timeLeftVomsProxy ()
Returns the life time left. for a proxy.
Returns:
int time left for the proxy
Definition at line 56 of file gridFunctions.py.
Referenced by checkVomsProxy().
Author
Generated automatically by Doxygen for libs3a from the source code.