.TH "python/gridFunctions.py" 3 "Fri Jan 30 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/gridFunctions.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBgridFunctions\fP"
.br
.RI "\fIThis module provides common functions for interaction with the local Tier2\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgridFunctions\&.getdcachelist\fP"
.br
.RI "\fIGet list of files with certain file extension in dCap folder recursively\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.timeLeftVomsProxy\fP"
.br
.RI "\fIReturns the life time left\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.checkVomsProxy\fP"
.br
.RI "\fIChecks if the proxy is valid longer than time\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.renewVomsProxy\fP"
.br
.RI "\fICreates a new vom proxy\&. \fP"
.ti -1c
.RI "def \fBgridFunctions\&.checkAndRenewVomsProxy\fP"
.br
.RI "\fIChecks if the proxy is valid longer than time and renew if needed\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
