HistClass
NAME
HistClass -
Functions to have easy histogram handling.
SYNOPSIS
Functions
static SUPPRESS_NOT_USED_WARN void CreateHisto (Int_t n_histos, const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create a number of 1D histograms in the histo map.
static SUPPRESS_NOT_USED_WARN void CreateHisto (Int_t n_histos, const char *name, const char *particle, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create a number of 1D histograms in the histo map for a specific particle.
static SUPPRESS_NOT_USED_WARN void CreateHistoUnchangedName (const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create a 1D histogram in the histo map without the standard histogram naming convention (h1_...).
SUPPRESS_NOT_USED_WARN static const void CreateHisto (const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create one 1D histograms in the histo map.
SUPPRESS_NOT_USED_WARN static const void CreateHisto (const char *name, const char *particle, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create one 1D histogram in the histo map for a specific particle.
SUPPRESS_NOT_USED_WARN static const void CreateHisto (boost::basic_format< char > name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle='')
Function to create one 1D histograms in the histo map with a boost name as input.
static SUPPRESS_NOT_USED_WARN void CreateHisto (const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t ylow, Double_t yup, TString xtitle='', TString ytitle='')
Function to create one 2D histograms in the histo map.
static SUPPRESS_NOT_USED_WARN void CreateHisto (Int_t n_histos, const char *name, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t ylow, Double_t yup, TString xtitle='', TString ytitle='')
Function to create a number of 2D histograms in the histo map.
static SUPPRESS_NOT_USED_WARN void CreateNSparse (const char *name, int dimension, int *bins, double *xmin, double *xmax, string axisTitle[])
Function to create one NSparse in the nSparse map.
static SUPPRESS_NOT_USED_WARN void CreateTree (const char *name, const char *varlist, int bufsize)
Function to create one NtupleD in the NtupleD map.
static SUPPRESS_NOT_USED_WARN void CreateTree (std::map< std::string, float > &m, const char *name)
Function to create one Tree in the TTree map.
static void Fill (Int_t n_histo, const char *name, double value, double weight)
Function to fill an event in a 1D histogram of the map.
static SUPPRESS_NOT_USED_WARN void Fill (Int_t n_histo, std::string name, double value, double weight)
Function to fill an event in a 1D histogram of the map with a string as histo name.
static SUPPRESS_NOT_USED_WARN void Fill (const char *name, double value, double weight)
Function to fill an event in a 1D histogram of the map without histo number.
static SUPPRESS_NOT_USED_WARN void Fill (const char *name, double valuex, double valuey, double weight)
Function to fill an event in a 2D histogram of the map.
static void Fill (Int_t n_histo, const char *name, double valuex, double valuey, double weight)
Function to fill an event in a 2D histogram of the map.
static SUPPRESS_NOT_USED_WARN void FillSparse (const char *name, int n,...)
Function to fill an event in a nSparse of the nSparse map.
static SUPPRESS_NOT_USED_WARN void FillTree (const char *name, double *values)
Function to fill an event in a NTupleD of the map.
static SUPPRESS_NOT_USED_WARN void FillTree (const char *name)
Function to fill an event in a TTree of the map.
static SUPPRESS_NOT_USED_WARN void Write (Int_t n_histo, const char *name)
Function to write one 1D histogram of the map.
static SUPPRESS_NOT_USED_WARN void Write (const char *name)
Function to write one 1D histogram of the map without number.
static SUPPRESS_NOT_USED_WARN void WriteAll (const char *name='')
Function to write many 1D histograms of the map.
static SUPPRESS_NOT_USED_WARN void WriteAll2 (const char *name='')
Function to write many 2D histograms of the map.
SUPPRESS_NOT_USED_WARN void split (const std::string &s, char delim, std::vector< std::string > &elems)
Function split a string at a delimiter.
SUPPRESS_NOT_USED_WARN std::vector< std::string > split (const std::string &s, char delim)
Function split a string at a delimiter and return the results.
static SUPPRESS_NOT_USED_WARN void WriteAll (const char *name, const char *contains_i)
Function to write many 1D histograms which contain specific strings of the map.
static SUPPRESS_NOT_USED_WARN void WriteAll2 (const char *name, const char *contains_i)
Function to write many 2D histograms which contain specific strings of the map.
static SUPPRESS_NOT_USED_WARN void WriteAll (const char *name, const char *contains_i, const char *vetos_i)
Function to write many 1D histograms which (not) contain specific strings of the map.
static SUPPRESS_NOT_USED_WARN void WriteAll2 (const char *name, const char *contains_i, const char *vetos_i)
Function to write many 2D histograms which (not) contain specific strings of the map.
static SUPPRESS_NOT_USED_WARN void WriteAllTrees (const char *name='')
Function to write many TTrees and TNtupleDs of the maps.
static SUPPRESS_NOT_USED_WARN void WriteN (const char *name='')
Function to write many TNsparses of the map.
static SUPPRESS_NOT_USED_WARN void Write2 (const char *name)
Function to write one 2D histogram of the map.
static SUPPRESS_NOT_USED_WARN void SetToZero (Int_t n_histo, const char *name)
Function to set all negative bin contents to zero for a 1D histogram.
static SUPPRESS_NOT_USED_WARN TH1D * ReturnHist (const char *name)
Function to get one 1D histogram from the map without number.
static SUPPRESS_NOT_USED_WARN void NameBins (const char *name, const uint n_bins, TString *d_mydisc)
Function to give one 1D histogram from the map alphanumeric bin labels without number.
static SUPPRESS_NOT_USED_WARN void NameBins (Int_t n_histo, const char *name, const uint n_bins, TString *d_mydisc)
Function to give one 1D histogram from the map alphanumeric bin labels.
Variables
static std::map< std::string, TH1D * > histo
static std::map< std::string, TH2D * > histo2
static std::map< std::string, THnSparseD * > histon
static std::map< std::string, TNtupleD * > ttupple
static std::map< std::string, TTree * > trees
Detailed Description
Functions to have easy histogram handling.
In this namespace different functions to interact with the histogram map are included, to create, fill and write histograms in a convinient way.
Function Documentation
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHisto (Int_t n_histos, const char * name, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t ylow, Double_t yup, TString xtitle = '', TString ytitle = '') [static]
Function to create a number of 2D histograms in the histo map. Parameters:
n_histos Number of histograms that should be created with different numbers
name Name of the histogram that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
nbinsy Number of bins on the y-axis
ylow Lower edge of the y-axis
yup Upper edge of the y-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
ytitle Optinal title of the y-axis (DEFAULT = '')
Definition at line 174 of file HistClass.hh.
References histo2.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHisto (const char * name, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t ylow, Double_t yup, TString xtitle = '', TString ytitle = '') [static]
Function to create one 2D histograms in the histo map. Parameters:
name Name of the histogram that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
nbinsy Number of bins on the y-axis
ylow Lower edge of the y-axis
yup Upper edge of the y-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
ytitle Optinal title of the y-axis (DEFAULT = '')
Definition at line 152 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, and histo2.
SUPPRESS_NOT_USED_WARN static const void HistClass::CreateHisto (boost::basic_format< char > name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle = '') [static]
Function to create one 1D histograms in the histo map with a boost name as input. Parameters:
name Name of the histogram that should be created (boost::basic_format)
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 135 of file HistClass.hh.
References CreateHisto().
SUPPRESS_NOT_USED_WARN static const void HistClass::CreateHisto (const char * name, const char * particle, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle = '') [static]
Function to create one 1D histogram in the histo map for a specific particle. Parameters:
name Name of the histograms that should be created
particle Name of the particle for which the histograms are created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 119 of file HistClass.hh.
References histo.
SUPPRESS_NOT_USED_WARN static const void HistClass::CreateHisto (const char * name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle = '') [static]
Function to create one 1D histograms in the histo map. Parameters:
name Name of the histogram that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 102 of file HistClass.hh.
References histo.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHisto (Int_t n_histos, const char * name, const char * particle, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle = '') [static]
Function to create a number of 1D histograms in the histo map for a specific particle. Parameters:
n_histos Number of histograms that should be created with different numbers
name Name of the histograms that should be created
particle Name of the particle for which the histograms are created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 68 of file HistClass.hh.
References histo.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHisto (Int_t n_histos, const char * name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle = '') [static]
Function to create a number of 1D histograms in the histo map. Parameters:
n_histos Number of histograms that should be created with different numbers
name Name of the histograms that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 48 of file HistClass.hh.
References histo.
Referenced by CreateHisto().
static SUPPRESS_NOT_USED_WARN void HistClass::CreateHistoUnchangedName (const char * name, Int_t nbinsx, Double_t xlow, Double_t xup, TString xtitle = '') [static]
Function to create a 1D histogram in the histo map without the standard histogram naming convention (h1_...). Parameters:
name Name of the histograms that should be created
nbinsx Number of bins on the x-axis
xlow Lower edge of the x-axis
xup Upper edge of the x-axis
xtitle Optinal title of the x-axis (DEFAULT = '')
Definition at line 86 of file HistClass.hh.
References histo.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateNSparse (const char * name, int dimension, int * bins, double * xmin, double * xmax, string axisTitle[]) [static]
Function to create one NSparse in the nSparse map. Parameters:
name Name of the NSparse that should be created
dimension Number of dimensions that the NSparse should have
bins Array with the number of bins for each dimension
xmin Array of the lower edge of the axis for each dimension
xmax Array of the upper edge of the axis for each dimension
axisTitle[] Array of the axis title for each dimension
Definition at line 194 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, and histon.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateTree (std::map< std::string, float > & m, const char * name) [static]
Function to create one Tree in the TTree map. Parameters:
m Map of the name and variable that should be matched to each branch
name Name of the TTree that should be created
Definition at line 221 of file HistClass.hh.
References trees.
static SUPPRESS_NOT_USED_WARN void HistClass::CreateTree (const char * name, const char * varlist, int bufsize) [static]
Function to create one NtupleD in the NtupleD map. Parameters:
name Name of the NSparse that should be created
varlist Colon sepereated list with the name of the branches that should be created
bufsize Buffer size that the NtupleD should have
Definition at line 210 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, and ttupple.
static void HistClass::Fill (Int_t n_histo, const char * name, double valuex, double valuey, double weight) [static]
Function to fill an event in a 2D histogram of the map. This function fills one value with one weight for one event in one specific histogram. The function also checks if the histogram exists in the map, otherwise it will print an error message.
Parameters:
n_histo Number of the histogram that should be filled
name Name of the histogram which should be filled
valuex x-value that should be filled
valuey y-value that should be filled
weight Weight of the event that should be filled
Definition at line 311 of file HistClass.hh.
References histo2.
static SUPPRESS_NOT_USED_WARN void HistClass::Fill (const char * name, double valuex, double valuey, double weight) [static]
Function to fill an event in a 2D histogram of the map. Parameters:
name Name of the histogram which should be filled
valuex x-value that should be filled
valuey y-value that should be filled
weight Weight of the event that should be filled
Definition at line 294 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, and histo2.
static SUPPRESS_NOT_USED_WARN void HistClass::Fill (const char * name, double value, double weight) [static]
Function to fill an event in a 1D histogram of the map without histo number. This function fills one value with one weight for one event in one specific histogram. The function also checks if the histogram exists in the map, otherwise it will print an error message.
Parameters:
name Name of the histogram which should be filled
value Value that should be filled
weight Weight of the event that should be filled
Definition at line 270 of file HistClass.hh.
References histo.
static SUPPRESS_NOT_USED_WARN void HistClass::Fill (Int_t n_histo, std::string name, double value, double weight) [static]
Function to fill an event in a 1D histogram of the map with a string as histo name. Parameters:
n_histo Number of the histogram that should be filled
name Name of the histogram which should be filled (std string)
value Value that should be filled
weight Weight of the event that should be filled
Definition at line 256 of file HistClass.hh.
References Fill().
static void HistClass::Fill (Int_t n_histo, const char * name, double value, double weight) [static]
Function to fill an event in a 1D histogram of the map. This function fills one value with one weight for one event in one specific histogram. The function also checks if the histogram exists in the map, otherwise it will print an error message.
Parameters:
n_histo Number of the histogram that should be filled
name Name of the histogram which should be filled
value Value that should be filled
weight Weight of the event that should be filled
Definition at line 239 of file HistClass.hh.
References histo.
Referenced by Fill().
static SUPPRESS_NOT_USED_WARN void HistClass::FillSparse (const char * name, int n, ...) [static]
Function to fill an event in a nSparse of the nSparse map. This function fills one value with one event in one specific nSparse. The function also checks if the nSparse exists in the map, otherwise it will print an error message.
Parameters:
name Name of the n which should be filled
n
...
Todo
complete the function
Definition at line 331 of file HistClass.hh.
References histon.
static SUPPRESS_NOT_USED_WARN void HistClass::FillTree (const char * name) [static]
Function to fill an event in a TTree of the map. Parameters:
name Name of the TTree which should be filled
Definition at line 363 of file HistClass.hh.
References trees.
static SUPPRESS_NOT_USED_WARN void HistClass::FillTree (const char * name, double * values) [static]
Function to fill an event in a NTupleD of the map. Parameters:
name Name of the NTupleD which should be filled
values Array of values that should be filled
Definition at line 353 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, and ttupple.
static SUPPRESS_NOT_USED_WARN void HistClass::NameBins (Int_t n_histo, const char * name, const uint n_bins, TString * d_mydisc) [static]
Function to give one 1D histogram from the map alphanumeric bin labels. Parameters:
n_histo Number of the histogram that should get bin names
name Name of the histogram that should get bin names
n_bins of bins that should be renamed
d_mydisc Array with the names that th bins should get
Definition at line 733 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, and histo.
static SUPPRESS_NOT_USED_WARN void HistClass::NameBins (const char * name, const uint n_bins, TString * d_mydisc) [static]
Function to give one 1D histogram from the map alphanumeric bin labels without number. Parameters:
name Name of the histogram that should get bin names
n_bins of bins that should be renamed
d_mydisc Array with the names that th bins should get
Definition at line 716 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, and histo.
static SUPPRESS_NOT_USED_WARN TH1D* HistClass::ReturnHist (const char * name) [static]
Function to get one 1D histogram from the map without number. Parameters:
name Name of the histogram that should be returned
Returns:
histo Returned histogram
Definition at line 699 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, and histo.
static SUPPRESS_NOT_USED_WARN void HistClass::SetToZero (Int_t n_histo, const char * name) [static]
Function to set all negative bin contents to zero for a 1D histogram. Parameters:
n_histo Number of the histogram that should be modified
name Name of the histogram that should be modified
Definition at line 682 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, and histo.
SUPPRESS_NOT_USED_WARN std::vector<std::string> HistClass::split (const std::string & s, char delim)
Function split a string at a delimiter and return the results. This function splits a given string at a given delimineter, and returns the resulting substrings as a vector.
Parameters:
&s String that should be split
delim Delimiter where the string should be split
Returns:
[out] elems Vector in which the substrings were pushed
Definition at line 469 of file HistClass.hh.
References split().
SUPPRESS_NOT_USED_WARN void HistClass::split (const std::string & s, char delim, std::vector< std::string > & elems)
Function split a string at a delimiter. Example to create a nice folder structure in your output folder //void specialAna::channel_writer(TFile* file, const char* channel) { //file1->cd(); //file1->mkdir(channel); //for ( int i = 0; i < channel_stages[channel]; i++) { //char n_satge = (char)(((int)'0')+i); //file1->mkdir(TString::Format('%s/Stage_%c', channel, n_satge)); //file1->cd(TString::Format('%s/Stage_%c/', channel, n_satge)); //HistClassWriteAll(TString::Format('_%s_', channel),TString::Format('%s:_%c_', channel, n_satge),TString::Format('sys')); //file1->cd(); //file1->mkdir(TString::Format('%s/Stage_%c/sys', channel, n_satge)); //file1->cd(TString::Format('%s/Stage_%c/sys/', channel, n_satge)); //HistClassWriteAll(TString::Format('_%s_', channel),TString::Format('_%c_:sys', n_satge)); //} //file1->cd(); //}
This function splits a given string at a given delimineter, and pushes the results in a given vector.
Parameters:
&s String that should be split
delim Delimiter where the string should be split
&elems Vector in which the substrings should be pushed
Definition at line 453 of file HistClass.hh.
Referenced by split(), WriteAll(), and WriteAll2().
static SUPPRESS_NOT_USED_WARN void HistClass::Write (const char * name) [static]
Function to write one 1D histogram of the map without number. Parameters:
name Name of the histogram that should be written
Definition at line 383 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, and histo.
static SUPPRESS_NOT_USED_WARN void HistClass::Write (Int_t n_histo, const char * name) [static]
Function to write one 1D histogram of the map. Parameters:
n_histo Number of the histogram that should be written
name Name of the histogram that should be written
Definition at line 373 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, and histo.
Referenced by WriteAll(), WriteAll2(), WriteAllTrees(), and WriteN().
static SUPPRESS_NOT_USED_WARN void HistClass::Write2 (const char * name) [static]
Function to write one 2D histogram of the map. Parameters:
name Name of the histogram that should be written
Definition at line 671 of file HistClass.hh.
References html_to_bash_ascii_converter::dummy, and histo2.
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAll (const char * name, const char * contains_i, const char * vetos_i) [static]
Function to write many 1D histograms which (not) contain specific strings of the map. This function writes all histograms of the map with that contain the given string in there name. The written histo- grams also have to contain a list of strings that are sepe- rated by a ':'. In this version also a list of strings that should not be contained in the histogram name can be given.
Parameters:
name String that all histogram names that should be written contain
contains_i String that of names (seperated by ':') that the histogram name should contain
vetos_i String that of names (seperated by ':') that the histogram name should not contain
Definition at line 550 of file HistClass.hh.
References histo, split(), and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAll (const char * name, const char * contains_i) [static]
Function to write many 1D histograms which contain specific strings of the map. This function writes all histograms of the map with that contain the given string in there name. The written histo- grams also have to contain a list of strings that are sepe- rated by a ':'.
Parameters:
name String that all histogram names that should be written contain
contains_i String that of names (seperated by ':') that the histogram name should contain
Definition at line 484 of file HistClass.hh.
References histo, split(), and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAll (const char * name = '') [static]
Function to write many 1D histograms of the map. This function writes all histograms of the map with the default options, otherwise it writes all histograms that contain the given string in there name.
Parameters:
name Optional string that all histogram names that should be written contain (DEFAULT = '')
Definition at line 396 of file HistClass.hh.
References histo, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAll2 (const char * name, const char * contains_i, const char * vetos_i) [static]
Function to write many 2D histograms which (not) contain specific strings of the map. This function writes all histograms of the map with that contain the given string in there name. The written histo- grams also have to contain a list of strings that are sepe- rated by a ':'. In this version also a list of strings that should not be contained in the histogram name can be given.
Parameters:
name String that all histogram names that should be written contain
contains_i String that of names (seperated by ':') that the histogram name should contain
vetos_i String that of names (seperated by ':') that the histogram name should not contain
Definition at line 592 of file HistClass.hh.
References histo2, split(), and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAll2 (const char * name, const char * contains_i) [static]
Function to write many 2D histograms which contain specific strings of the map. This function writes all histograms of the map with that contain the given string in there name. The written histo- grams also have to contain a list of strings that are sepe- rated by a ':'.
Parameters:
name String that all histogram names that should be written contain
contains_i String that of names (seperated by ':') that the histogram name should contain
Definition at line 516 of file HistClass.hh.
References histo2, split(), and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAll2 (const char * name = '') [static]
Function to write many 2D histograms of the map. This function writes all histograms of the map with the default options, otherwise it writes all histograms that contain the given string in there name.
Parameters:
name Optional string that all histogram names that should be written contain (DEFAULT = '')
Definition at line 415 of file HistClass.hh.
References histo2, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteAllTrees (const char * name = '') [static]
Function to write many TTrees and TNtupleDs of the maps. This function writes all TTrees and TNtupleDs of the maps with the default options, otherwise it writes all histograms that contain the given string in there name.
Parameters:
name Optional string that all TTrees or TNtupleDs names that should be written contain (DEFAULT = '')
Definition at line 630 of file HistClass.hh.
References trees, ttupple, and Write().
static SUPPRESS_NOT_USED_WARN void HistClass::WriteN (const char * name = '') [static]
Function to write many TNsparses of the map. This function writes all nSparses of the map with the default options, otherwise it writes all histograms that contain the given string in there name.
Parameters:
name Optional string that all nSparses names that should be written contain (DEFAULT = '')
Definition at line 655 of file HistClass.hh.
References histon, and Write().
Variable Documentation
std::map<std::string, TH1D * > HistClass::histo [static]"Map of a string and a TH1D histogram, for easy 1D histogram handling.
Definition at line 33 of file HistClass.hh.
Referenced by CreateHisto(), CreateHistoUnchangedName(), Fill(), NameBins(), ReturnHist(), SetToZero(), Write(), and WriteAll().
std::map<std::string, TH2D * > HistClass::histo2 [static]"Map of a string and a TH2D histogram, for easy 2D histogram handling.
Definition at line 34 of file HistClass.hh.
Referenced by CreateHisto(), Fill(), Write2(), and WriteAll2().
std::map<std::string, THnSparseD * > HistClass::histon [static]"Map of a string and a THnSparseD histogram, for easy nSparse handling.
Definition at line 35 of file HistClass.hh.
Referenced by CreateNSparse(), FillSparse(), and WriteN().
std::map<std::string, TTree * > HistClass::trees [static]"Map of a string and a TTree histogram, for easy tree handling.
Definition at line 37 of file HistClass.hh.
Referenced by CreateTree(), FillTree(), and WriteAllTrees().
std::map<std::string, TNtupleD * > HistClass::ttupple [static]"Map of a string and a TNtupleD histogram, for easy Ntuple handling.
Definition at line 36 of file HistClass.hh.
Referenced by CreateTree(), FillTree(), and WriteAllTrees().
Author
Generated automatically by Doxygen for libs3a from the source code.