.TH "python/html_to_bash_ascii_converter.py" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/html_to_bash_ascii_converter.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBhtml_to_bash_ascii_converter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBhtml_to_bash_ascii_converter\&._str2hex\fP"
.br
.ti -1c
.RI "def \fBhtml_to_bash_ascii_converter\&._strip_hash\fP"
.br
.ti -1c
.RI "def \fBhtml_to_bash_ascii_converter\&._create_dicts\fP"
.br
.ti -1c
.RI "def \fBhtml_to_bash_ascii_converter\&.short2rgb\fP"
.br
.ti -1c
.RI "def \fBhtml_to_bash_ascii_converter\&.print_all\fP"
.br
.ti -1c
.RI "def \fBhtml_to_bash_ascii_converter\&.rgb2short\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBhtml_to_bash_ascii_converter\&.__author__\fP = 'Micah Elliott http://MicahElliott\&.com'"
.br
.ti -1c
.RI "string \fBhtml_to_bash_ascii_converter\&.__version__\fP = '0\&.1'"
.br
.ti -1c
.RI "string \fBhtml_to_bash_ascii_converter\&.__copyright__\fP = 'Copyright (C) 2011 Micah Elliott\&. All rights reserved\&.'"
.br
.ti -1c
.RI "string \fBhtml_to_bash_ascii_converter\&.__license__\fP = 'WTFPL http://sam\&.zoy\&.org/wtfpl/'"
.br
.ti -1c
.RI "list \fBhtml_to_bash_ascii_converter\&.CLUT\fP"
.br
.ti -1c
.RI "tuple \fBhtml_to_bash_ascii_converter\&.file_name\fP = raw_input('Give me a file name to convert!')"
.br
.ti -1c
.RI "tuple \fBhtml_to_bash_ascii_converter\&.file_out\fP = raw_input('Give me an output file name!')"
.br
.ti -1c
.RI "tuple \fBhtml_to_bash_ascii_converter\&.ins\fP = open( file_name, 'r' )"
.br
.ti -1c
.RI "list \fBhtml_to_bash_ascii_converter\&.array\fP = []"
.br
.ti -1c
.RI "list \fBhtml_to_bash_ascii_converter\&.new_array\fP = []"
.br
.ti -1c
.RI "\fBhtml_to_bash_ascii_converter\&.dummy\fP = item"
.br
.ti -1c
.RI "list \fBhtml_to_bash_ascii_converter\&.dummy2\fP = dummy[dummy\&.find('<span'):dummy\&.find(';'>')+3] arg = dummy[dummy\&.find(': #')+3:dummy\&.find(';'>')]"
.br
.ti -1c
.RI "tuple \fBhtml_to_bash_ascii_converter\&.file\fP = open(file_out, 'w')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
