.TH "lheanalyzer.LHEFile" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lheanalyzer.LHEFile \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__iter__\fP"
.br
.ti -1c
.RI "def \fBnext\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfilename\fP"
.br
.ti -1c
.RI "\fBfp\fP"
.br
.ti -1c
.RI "\fBlineCounter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file lheanalyzer\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lheanalyzer\&.LHEFile\&.__init__ (self, filename, forcegzipped = \fCFalse\fP)"

.PP
Definition at line 54 of file lheanalyzer\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lheanalyzer\&.LHEFile\&.__iter__ (self)"

.PP
Definition at line 64 of file lheanalyzer\&.py\&.
.SS "def lheanalyzer\&.LHEFile\&.next (self)"

.PP
Definition at line 66 of file lheanalyzer\&.py\&.
.PP
References lheanalyzer\&.LHEFile\&.fp, and lheanalyzer\&.LHEFile\&.lineCounter\&.
.SH "Member Data Documentation"
.PP 
.SS "lheanalyzer\&.LHEFile\&.filename"

.PP
Definition at line 55 of file lheanalyzer\&.py\&.
.SS "lheanalyzer\&.LHEFile\&.fp"

.PP
Definition at line 57 of file lheanalyzer\&.py\&.
.PP
Referenced by lheanalyzer\&.LHEFile\&.next()\&.
.SS "lheanalyzer\&.LHEFile\&.lineCounter"

.PP
Definition at line 60 of file lheanalyzer\&.py\&.
.PP
Referenced by lheanalyzer\&.LHEFile\&.next()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
