.TH "lheanalyzer::LorentzVector" 3 "30 Jan 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lheanalyzer::LorentzVector \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBadd\fP"
.br
.ti -1c
.RI "def \fBinvariantMass\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpx\fP"
.br
.ti -1c
.RI "\fBpy\fP"
.br
.ti -1c
.RI "\fBpz\fP"
.br
.ti -1c
.RI "\fBenergy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 119 of file lheanalyzer.py.
.SH "Member Function Documentation"
.PP 
.SS "def lheanalyzer::LorentzVector::__init__ ( self,  momentum)"
.PP
Definition at line 120 of file lheanalyzer.py.
.SS "def lheanalyzer::LorentzVector::add ( self,  p)"
.PP
Definition at line 125 of file lheanalyzer.py.
.SS "def lheanalyzer::LorentzVector::invariantMass ( self)"
.PP
Definition at line 130 of file lheanalyzer.py.
.SH "Member Data Documentation"
.PP 
.SS "\fBlheanalyzer::LorentzVector::energy\fP"
.PP
Definition at line 124 of file lheanalyzer.py.
.SS "\fBlheanalyzer::LorentzVector::px\fP"
.PP
Definition at line 121 of file lheanalyzer.py.
.SS "\fBlheanalyzer::LorentzVector::py\fP"
.PP
Definition at line 122 of file lheanalyzer.py.
.SS "\fBlheanalyzer::LorentzVector::pz\fP"
.PP
Definition at line 123 of file lheanalyzer.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code.
