.TH "lheanalyzer" 3 "30 Jan 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lheanalyzer \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLHEFileFormatError\fP"
.br
.ti -1c
.RI "class \fBParticle\fP"
.br
.ti -1c
.RI "class \fBEvent\fP"
.br
.ti -1c
.RI "class \fBProcess\fP"
.br
.ti -1c
.RI "class \fBLHEFile\fP"
.br
.ti -1c
.RI "class \fBLHEAnalysis\fP"
.br
.ti -1c
.RI "class \fBLorentzVector\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBinvariantMass\fP"
.br
.ti -1c
.RI "def \fBtransverseMass\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lheanalyzer::invariantMass ( p0,  particles)"
.PP
Definition at line 134 of file lheanalyzer.py.
.SS "def lheanalyzer::transverseMass ( p0,  p1)"
.PP
Definition at line 141 of file lheanalyzer.py.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code.
