.TH "hooks/pre-commit.py" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hooks/pre-commit.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBpre-commit\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBpre-commit\&.gitController\fP = GitHookController()"
.br
.ti -1c
.RI "tuple \fBpre-commit\&.changed\fP = gitController\&.parse_pre_commit()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
