.TH "examples/cesubmit/specialAna/remote_example.py" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/cesubmit/specialAna/remote_example.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBremote_example\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBremote_example\&.getFilesfromFile\fP"
.br
.ti -1c
.RI "def \fBremote_example\&.readDcachePickle\fP"
.br
.ti -1c
.RI "def \fBremote_example\&.makeExe\fP"
.br
.ti -1c
.RI "def \fBremote_example\&.prepare_teli\fP"
.br
.ti -1c
.RI "def \fBremote_example\&.main\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBremote_example\&.log\fP = logging\&.getLogger( 'remote' )"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
