remote_example
NAME
remote_example -
SYNOPSIS
Functions
def getFilesfromFile
def readDcachePickle
def makeExe
def prepare_teli
def main
Variables
tuple log = logging.getLogger( 'remote' )
Function Documentation
def remote_example.getFilesfromFile (cfgFile)
Definition at line 12 of file remote_example.py.
References gridFunctions.getdcachelist(), and readDcachePickle().
Referenced by main().
def remote_example.main ()
Definition at line 177 of file remote_example.py.
References checkEnvironment.checkEnvironment(), getFilesfromFile(), makeExe(), and prepare_teli().
def remote_example.makeExe (user)
Definition at line 80 of file remote_example.py.
Referenced by main().
def remote_example.prepare_teli (options)
Definition at line 125 of file remote_example.py.
References TimedCall.retry().
Referenced by main().
def remote_example.readDcachePickle (file)
Definition at line 54 of file remote_example.py.
Referenced by getFilesfromFile().
Variable Documentation
tuple remote_example.log = logging.getLogger( 'remote' )
Definition at line 10 of file remote_example.py.
Author
Generated automatically by Doxygen for Aachen-3A from the source code.