.TH "remote_example" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
remote_example \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgetFilesfromFile\fP"
.br
.ti -1c
.RI "def \fBreadDcachePickle\fP"
.br
.ti -1c
.RI "def \fBmakeExe\fP"
.br
.ti -1c
.RI "def \fBprepare_teli\fP"
.br
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBlog\fP = logging\&.getLogger( 'remote' )"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def remote_example\&.getFilesfromFile (cfgFile)"

.PP
Definition at line 12 of file remote_example\&.py\&.
.PP
References gridFunctions\&.getdcachelist(), and readDcachePickle()\&.
.PP
Referenced by main()\&.
.SS "def remote_example\&.main ()"

.PP
Definition at line 177 of file remote_example\&.py\&.
.PP
References checkEnvironment\&.checkEnvironment(), getFilesfromFile(), makeExe(), and prepare_teli()\&.
.SS "def remote_example\&.makeExe (user)"

.PP
Definition at line 80 of file remote_example\&.py\&.
.PP
Referenced by main()\&.
.SS "def remote_example\&.prepare_teli (options)"

.PP
Definition at line 125 of file remote_example\&.py\&.
.PP
References TimedCall\&.retry()\&.
.PP
Referenced by main()\&.
.SS "def remote_example\&.readDcachePickle (file)"

.PP
Definition at line 54 of file remote_example\&.py\&.
.PP
Referenced by getFilesfromFile()\&.
.SH "Variable Documentation"
.PP 
.SS "tuple remote_example\&.log = logging\&.getLogger( 'remote' )"

.PP
Definition at line 10 of file remote_example\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
