.TH "python/rootplotlib.py" 3 "Fri Jan 30 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/rootplotlib.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrootplotlib\&.CmsDecoration\fP"
.br
.ti -1c
.RI "class \fBrootplotlib\&.Legend\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBrootplotlib\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBrootplotlib\&.Latex\fP"
.br
.ti -1c
.RI "def \fBrootplotlib\&.init\fP"
.br
.ti -1c
.RI "def \fBrootplotlib\&.tdrStyle\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
