.TH "rootplotlib.CmsDecoration" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rootplotlib.CmsDecoration \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBDraw\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcmsTextFont\fP"
.br
.ti -1c
.RI "\fBlumiTextFont\fP"
.br
.ti -1c
.RI "\fBextraTextFont\fP"
.br
.ti -1c
.RI "\fBadditionalTextFont\fP"
.br
.ti -1c
.RI "\fBcmsTextSize\fP"
.br
.ti -1c
.RI "\fBlumiTextSize\fP"
.br
.ti -1c
.RI "\fBextraTextSize\fP"
.br
.ti -1c
.RI "\fBadditionalTextSize\fP"
.br
.ti -1c
.RI "\fBadditionalTextVspace\fP"
.br
.ti -1c
.RI "\fBlumiTextOffset\fP"
.br
.ti -1c
.RI "\fBextraTextOffset\fP"
.br
.ti -1c
.RI "\fBrelPosX\fP"
.br
.ti -1c
.RI "\fBrelPosY\fP"
.br
.ti -1c
.RI "\fBrelExtraDY\fP"
.br
.ti -1c
.RI "\fBlumiText\fP"
.br
.ti -1c
.RI "\fBhspace\fP"
.br
.ti -1c
.RI "\fBpad\fP"
.br
.ti -1c
.RI "\fBreferenceHeight\fP"
.br
.ti -1c
.RI "\fBalign\fP"
.br
.ti -1c
.RI "\fBvalign\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file rootplotlib\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def rootplotlib\&.CmsDecoration\&.__init__ (self, extraText = \fCNone\fP, additionalText = \fCNone\fP, lumiText = \fC'19\&.7 fb^{-1} (8 TeV)'\fP, align = \fC'left'\fP, valign = \fC'top'\fP, vspace = \fC0\fP, hspace = \fC0\fP, referenceHeight = \fCNone\fP, pad = \fCNone\fP)"

.PP
Definition at line 18 of file rootplotlib\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def rootplotlib\&.CmsDecoration\&.Draw (self)"

.PP
Definition at line 51 of file rootplotlib\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "rootplotlib\&.CmsDecoration\&.additionalTextFont"

.PP
Definition at line 22 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.additionalTextSize"

.PP
Definition at line 26 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.additionalTextVspace"

.PP
Definition at line 27 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.align"

.PP
Definition at line 57 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.cmsTextFont"

.PP
Definition at line 19 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.cmsTextSize"

.PP
Definition at line 23 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.extraTextFont"

.PP
Definition at line 21 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.extraTextOffset"

.PP
Definition at line 29 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.extraTextSize"

.PP
Definition at line 25 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.hspace"

.PP
Definition at line 35 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.lumiText"

.PP
Definition at line 34 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.lumiTextFont"

.PP
Definition at line 20 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.lumiTextOffset"

.PP
Definition at line 28 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.lumiTextSize"

.PP
Definition at line 24 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.pad"

.PP
Definition at line 38 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.referenceHeight"

.PP
Definition at line 45 of file rootplotlib\&.py\&.
.PP
Referenced by rootplotlib\&.Legend\&.getTextWidth()\&.
.SS "rootplotlib\&.CmsDecoration\&.relExtraDY"

.PP
Definition at line 33 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.relPosX"

.PP
Definition at line 31 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.relPosY"

.PP
Definition at line 32 of file rootplotlib\&.py\&.
.SS "rootplotlib\&.CmsDecoration\&.valign"

.PP
Definition at line 78 of file rootplotlib\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
