.TH "rootplotlib" 3 "Fri Jan 30 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rootplotlib \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCmsDecoration\fP"
.br
.ti -1c
.RI "class \fBLegend\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBLatex\fP"
.br
.ti -1c
.RI "def \fBinit\fP"
.br
.ti -1c
.RI "def \fBtdrStyle\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def rootplotlib\&.init ()"

.PP
Definition at line 218 of file rootplotlib\&.py\&.
.PP
References tdrStyle()\&.
.SS "def rootplotlib\&.Latex (pad = \fCNone\fP)"

.PP
Definition at line 3 of file rootplotlib\&.py\&.
.SS "def rootplotlib\&.tdrStyle ()"

.PP
Definition at line 223 of file rootplotlib\&.py\&.
.PP
Referenced by init()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
