.TH "python/terminalFunctions.py" 3 "30 Jan 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python/terminalFunctions.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBterminalFunctions::bcolors\fP"
.br
.RI "\fIColor definition for terminal output. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBterminalFunctions\fP"
.br
.ti -1c
.RI "namespace \fBterminalFunctions::py\fP"
.br
.PP

.RI "\fIFunctions to be used for terminal output. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBterminalFunctions::getTerminalSize\fP"
.br
.RI "\fIFunction to get the size of the terminal. \fP"
.ti -1c
.RI "def \fBterminalFunctions::update_progress\fP"
.br
.RI "\fIFunction to create and update a progress bar. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code.
