.TH "terminalFunctions.py" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
terminalFunctions.py \- 
.PP
Functions to be used for terminal output\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Functions to be used for terminal output\&. 

Functions and classes for terminal output\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
