TimedCall
NAME
TimedCall -
SYNOPSIS
Classes
class TimeoutExpired
Functions
def call
def retry
Function Documentation
def TimedCall.call (timeout, args)
Run a command with a timeout after which it will be forcibly
killed.
Definition at line 8 of file TimedCall.py.
Referenced by retry().
def TimedCall.retry (N, timeout, args)
Try to run a call N times when it times out, then fail.
Definition at line 37 of file TimedCall.py.
References call().
Referenced by remote_example.prepare_teli().
Author
Generated automatically by Doxygen for Aachen-3A from the source code.