.TH "TimedCall" 3 "Thu Jan 29 2015" "Aachen-3A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimedCall \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTimeoutExpired\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcall\fP"
.br
.ti -1c
.RI "def \fBretry\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def TimedCall\&.call (timeout, args)"

.PP
.nf
Run a command with a timeout after which it will be forcibly
killed.

.fi
.PP
 
.PP
Definition at line 8 of file TimedCall\&.py\&.
.PP
Referenced by retry()\&.
.SS "def TimedCall\&.retry (N, timeout, args)"

.PP
.nf
Try to run a call N times when it times out, then fail.
.fi
.PP
 
.PP
Definition at line 37 of file TimedCall\&.py\&.
.PP
References call()\&.
.PP
Referenced by remote_example\&.prepare_teli()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aachen-3A from the source code\&.
